/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: 346c848eea0a584c737f635ec1f1e62f)
// Manually updated to add GASTOWN_ORG after adding GastownOrgDO (v2 migration).
// GIT_TOKEN_SERVICE RPC types (wrangler emits untyped `Service` for cross-worker bindings)
type GetTokenForRepoSuccess = {
	success: true;
	token: string;
	installationId: string;
	accountLogin: string;
	appType: 'standard' | 'lite';
};
type GetTokenForRepoFailure = {
	success: false;
	reason: 'database_not_configured' | 'invalid_repo_format' | 'no_installation_found' | 'invalid_org_id';
};
type GetTokenForRepoResult = GetTokenForRepoSuccess | GetTokenForRepoFailure;
type GitTokenService = {
	getTokenForRepo(params: { githubRepo: string; userId: string; orgId?: string }): Promise<GetTokenForRepoResult>;
	getToken(installationId: string, appType?: 'standard' | 'lite'): Promise<string>;
};
// WASTELAND_SERVICE RPC types — corresponds to WastelandRPCEntrypoint in services/wasteland
type WastelandRpcSuccess<T> = { success: true; data: T };
type WastelandRpcFailure = {
	success: false;
	code: 'NOT_FOUND' | 'PRECONDITION_FAILED' | 'INTERNAL_SERVER_ERROR' | 'UPSTREAM_ERROR';
	message: string;
};
type WastelandRpcResult<T> = WastelandRpcSuccess<T> | WastelandRpcFailure;
type WastelandService = {
	browseWantedBoard(params: {
		wastelandId: string;
		userId: string;
	}): Promise<WastelandRpcResult<Array<Record<string, unknown>>>>;
	claimWantedItem(params: {
		wastelandId: string;
		userId: string;
		itemId: string;
	}): Promise<WastelandRpcResult<{ success: true; pr_url: string | null }>>;
	postWantedItem(params: {
		wastelandId: string;
		userId: string;
		title: string;
		description: string;
		priority?: 'low' | 'medium' | 'high' | 'critical';
		type?: 'feature' | 'bug' | 'docs' | 'other';
		publish?: boolean;
	}): Promise<WastelandRpcResult<{ success: true; wantedId: string; pr_url: string | null }>>;
	markWantedItemDone(params: {
		wastelandId: string;
		userId: string;
		itemId: string;
		evidence: string;
	}): Promise<WastelandRpcResult<{ success: true; pr_url: string | null }>>;
};
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/gastown.worker");
		durableNamespaces: "GastownUserDO" | "GastownOrgDO" | "AgentIdentityDO" | "TownContainerDO" | "TownDO" | "AgentDO";
	}
	interface DevEnv {
		GASTOWN_AE: AnalyticsEngineDataset;
		GASTOWN_JWT_SECRET: SecretsStoreSecret;
		NEXTAUTH_SECRET: SecretsStoreSecret;
		ENVIRONMENT: "development";
		CF_ACCESS_TEAM: "engineering-e11";
		CF_ACCESS_AUD: "7f6eda4c0714f6ea2afb74a3f055db65659b67571a913eab42468636a9b8c8be";
		KILO_API_URL: "http://192.168.65.254:3000";
		GASTOWN_API_URL: "http://192.168.65.254:8787";
		WASTELAND_API_URL: "http://192.168.65.254:8787";
		GASTOWN_USER: DurableObjectNamespace<import("./src/gastown.worker").GastownUserDO>;
		GASTOWN_ORG: DurableObjectNamespace<import("./src/gastown.worker").GastownOrgDO>;
		AGENT_IDENTITY: DurableObjectNamespace<import("./src/gastown.worker").AgentIdentityDO>;
		TOWN: DurableObjectNamespace<import("./src/gastown.worker").TownDO>;
		TOWN_CONTAINER: DurableObjectNamespace<import("./src/gastown.worker").TownContainerDO>;
		AGENT: DurableObjectNamespace<import("./src/gastown.worker").AgentDO>;
		GIT_TOKEN_SERVICE: GitTokenService;
		WASTELAND_SERVICE: WastelandService;
		AI: Ai;
		AGENT_DB_SNAPSHOTS_KV: KVNamespace;
	}
	interface Env {
		GASTOWN_AE: AnalyticsEngineDataset;
		GASTOWN_JWT_SECRET: SecretsStoreSecret;
		NEXTAUTH_SECRET: SecretsStoreSecret;
		ENVIRONMENT: "development" | "production";
		CF_ACCESS_TEAM: "engineering-e11";
		CF_ACCESS_AUD: "7f6eda4c0714f6ea2afb74a3f055db65659b67571a913eab42468636a9b8c8be";
		KILO_API_URL: "http://192.168.65.254:3000" | "https://api.kilo.ai";
		GASTOWN_API_URL: "http://192.168.65.254:8787" | "https://gastown.kiloapps.io";
		WASTELAND_API_URL: "http://192.168.65.254:8787" | "https://wasteland.kiloapps.io";
		GASTOWN_USER: DurableObjectNamespace<import("./src/gastown.worker").GastownUserDO>;
		GASTOWN_ORG: DurableObjectNamespace<import("./src/gastown.worker").GastownOrgDO>;
		AGENT_IDENTITY: DurableObjectNamespace<import("./src/gastown.worker").AgentIdentityDO>;
		TOWN: DurableObjectNamespace<import("./src/gastown.worker").TownDO>;
		TOWN_CONTAINER: DurableObjectNamespace<import("./src/gastown.worker").TownContainerDO>;
		AGENT: DurableObjectNamespace<import("./src/gastown.worker").AgentDO>;
		GIT_TOKEN_SERVICE: GitTokenService;
		WASTELAND_SERVICE: WastelandService;
		AI: Ai;
		AGENT_DB_SNAPSHOTS_KV: KVNamespace;
		HYPERDRIVE?: Hyperdrive;
		CF_VERSION_METADATA?: WorkerVersionMetadata;
		SENTRY_DSN?: string; // worker secret
		SENTRY_RELEASE?: string; // deploy-time --var
	}
}
interface Env extends Cloudflare.Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "ENVIRONMENT" | "CF_ACCESS_TEAM" | "CF_ACCESS_AUD" | "KILO_API_URL" | "GASTOWN_API_URL">> {}
}
