/**
 * Adds expiry dates to free, non-expiring credit transactions so they expire
 * after a configurable number of days (default 30) from when the script is run.
 *
 * The set of credits to expire is defined by a CSV file passed via --input.
 * The input.csv is generated by downloading the following Google Sheet as CSV:
 * https://docs.google.com/spreadsheets/d/1G8EAUD39Hn3C01qNnjvWSEQpG3te0HIgiSi0yMD-AZk/edit?gid=458053126#gid=458053126
 * Each CSV row specifies a (CREDIT_CATEGORY, DESCRIPTION) pair and whether it
 * should expire, along with an optional EXPIRE_IN_DAYS override.  An empty
 * DESCRIPTION matches any description for that category.
 *
 * The script queries by credit_category first (much faster than scanning all
 * users), then processes each affected user.
 *
 * For each affected user the script:
 *   1. Fetches all personal credit transactions (excluding org-scoped).
 *   2. Simulates what would expire on the per-credit expiry date using
 *      computeExpiration().
 *   3. Writes a JSONL log line with the user's current/projected balance and
 *      per-credit projected expired amounts.
 *   4. In --execute mode, sets expiry_date and expiration_baseline on the
 *      affected transactions and updates the user's next_credit_expiration_at.
 *
 * Usage:
 *   pnpm script src/scripts/d2026-03-18_expire-free-credits.ts --input=path/to/credits.csv
 *   pnpm script src/scripts/d2026-03-18_expire-free-credits.ts --input=path/to/credits.csv --execute
 *   pnpm script src/scripts/d2026-03-18_expire-free-credits.ts --input=path/to/credits.csv --batch-size=1000
 *   pnpm script src/scripts/d2026-03-18_expire-free-credits.ts --input=path/to/credits.csv --concurrency=20
 */

import '../lib/load-env';

import { createWriteStream, readFileSync } from 'node:fs';
import { mkdir } from 'node:fs/promises';
import path from 'node:path';
import { createInterface } from 'node:readline';
import { parse as csvParse } from 'csv-parse/sync';
import pLimit from 'p-limit';
import { db, closeAllDrizzleConnections } from '@/lib/drizzle';
import { credit_transactions, kilocode_users } from '@kilocode/db/schema';
import { and, eq, gt, isNull, sql, inArray } from 'drizzle-orm';
import { computeExpiration, type ExpiringTransaction } from '@/lib/creditExpiration';

// ── Constants ────────────────────────────────────────────────────────────────

const DEFAULT_EXPIRE_IN_DAYS = 30;

// ── Types ────────────────────────────────────────────────────────────────────

type CsvRow = {
  category: string;
  shouldExpire: boolean;
  description: string | null;
  expireInDays: number;
};

type PairKey = string;
const pairKey = (cat: string, desc: string | null): PairKey =>
  desc ? `${cat} | ${desc}` : `${cat} | (any)`;

type RowLookup = {
  shouldExpire: boolean;
  expireInDays: number;
  expiryDate: Date;
  expiryDateIso: string;
};

// ── CSV parsing ──────────────────────────────────────────────────────────────

function parseCsv(inputPath: string): {
  rows: CsvRow[];
  lookup: Map<PairKey, RowLookup>;
  categoriesToQuery: string[];
} {
  const content = readFileSync(inputPath, 'utf-8');
  const rawRows = csvParse(content, {
    columns: true,
    skip_empty_lines: true,
    trim: true,
  }) as Record<string, string>[];

  // Validate required columns
  const requiredColumns = ['CREDIT_CATEGORY', 'SHOULD_EXPIRE', 'DESCRIPTION', 'EXPIRE_IN_DAYS'];
  if (rawRows.length === 0) {
    throw new Error(`CSV file "${inputPath}" contains no data rows`);
  }
  const firstRow = rawRows[0];
  for (const col of requiredColumns) {
    if (!(col in firstRow)) {
      throw new Error(`CSV is missing required column: ${col}`);
    }
  }

  const rows: CsvRow[] = [];
  const lookup = new Map<PairKey, RowLookup>();
  const seenPairs = new Set<PairKey>();

  for (const raw of rawRows) {
    const category = raw['CREDIT_CATEGORY'] ?? '';
    const shouldExpire = (raw['SHOULD_EXPIRE'] ?? '').toUpperCase() === 'TRUE';
    const rawDescription = raw['DESCRIPTION'] ?? '';
    const description = rawDescription === '' ? null : rawDescription;
    const rawExpireInDays = raw['EXPIRE_IN_DAYS'] ?? '';
    let expireInDays: number;
    if (rawExpireInDays === '') {
      expireInDays = DEFAULT_EXPIRE_IN_DAYS;
    } else {
      const parsed = parseInt(rawExpireInDays, 10);
      if (isNaN(parsed) || parsed <= 0) {
        throw new Error(
          `Invalid EXPIRE_IN_DAYS value "${rawExpireInDays}" for category "${category}"`
        );
      }
      expireInDays = parsed;
    }

    const key = pairKey(category, description);
    if (seenPairs.has(key)) {
      console.warn(
        `  Warning: duplicate (category, description) pair in CSV: "${key}" — using first occurrence`
      );
      continue;
    }
    seenPairs.add(key);

    const row: CsvRow = { category, shouldExpire, description, expireInDays };
    rows.push(row);

    // Pre-compute expiry date: now + expireInDays, truncated to midnight UTC
    const expiryDate = new Date(Date.now() + expireInDays * 24 * 60 * 60 * 1000);
    expiryDate.setUTCHours(0, 0, 0, 0);
    const expiryDateIso = expiryDate.toISOString();

    lookup.set(key, { shouldExpire, expireInDays, expiryDate, expiryDateIso });
  }

  // Distinct categories that have at least one shouldExpire=true row
  const categoriesToQuery = [...new Set(rows.filter(r => r.shouldExpire).map(r => r.category))];

  return { rows, lookup, categoriesToQuery };
}

// ── Credit resolution ────────────────────────────────────────────────────────

function resolveCredit(
  lookup: Map<PairKey, RowLookup>,
  category: string,
  description: string | null
): RowLookup | null {
  // Try specific match first
  const specific = lookup.get(pairKey(category, description));
  if (specific) return specific;
  // Fall back to catch-all (null description)
  const catchAll = lookup.get(pairKey(category, null));
  if (catchAll) return catchAll;
  return null;
}

/** Resolve a credit that was already filtered to shouldExpire=true. Throws if no match. */
function resolveCreditOrThrow(
  lookup: Map<PairKey, RowLookup>,
  category: string,
  description: string | null
): RowLookup {
  const resolved = resolveCredit(lookup, category, description);
  if (!resolved) {
    throw new Error(
      `No CSV row found for (${category}, ${description ?? '(any)'}). This should not happen — credit passed the shouldExpire filter.`
    );
  }
  return resolved;
}

// ── Arg parsing ──────────────────────────────────────────────────────────────

function parseArgs(): {
  execute: boolean;
  yes: boolean;
  batchSize: number;
  concurrency: number;
  input: string;
} {
  const args = process.argv.slice(2);
  let execute = false;
  let yes = false;
  let batchSize = 10_000;
  let concurrency = 50;
  let input = '';

  for (const arg of args) {
    if (arg === '--execute') {
      execute = true;
    } else if (arg === '--yes' || arg === '-y') {
      yes = true;
    } else if (arg.startsWith('--batch-size=')) {
      const value = parseInt(arg.split('=')[1], 10);
      if (isNaN(value) || value <= 0) {
        console.error(`Invalid --batch-size value: ${arg}`);
        process.exit(1);
      }
      batchSize = value;
    } else if (arg.startsWith('--concurrency=')) {
      const value = parseInt(arg.split('=')[1], 10);
      if (isNaN(value) || value <= 0) {
        console.error(`Invalid --concurrency value: ${arg}`);
        process.exit(1);
      }
      concurrency = value;
    } else if (arg.startsWith('--input=')) {
      input = arg.slice('--input='.length);
    }
  }

  if (!input) {
    console.error('Missing required argument: --input=<path>');
    process.exit(1);
  }

  return { execute, yes, batchSize, concurrency, input };
}

// ── Process a single user ────────────────────────────────────────────────────

async function processUser(
  userId: string,
  affectedCredits: (typeof credit_transactions.$inferSelect)[],
  execute: boolean,
  output: ReturnType<typeof createWriteStream>,
  mutationLog: ReturnType<typeof createWriteStream>,
  lookup: Map<PairKey, RowLookup>
): Promise<{ creditsAffected: number; creditsSkipped: number; projectedExpiration: number }> {
  // 1. Fetch user info
  const [user] = await db
    .select({
      id: kilocode_users.id,
      microdollars_used: kilocode_users.microdollars_used,
      total_microdollars_acquired: kilocode_users.total_microdollars_acquired,
      next_credit_expiration_at: kilocode_users.next_credit_expiration_at,
    })
    .from(kilocode_users)
    .where(eq(kilocode_users.id, userId));

  if (!user) throw new Error(`User ${userId} not found`);

  // 2. Fetch all user credit transactions (excluding org-scoped) for simulation context
  const allTransactions = await db
    .select()
    .from(credit_transactions)
    .where(
      and(eq(credit_transactions.kilo_user_id, userId), isNull(credit_transactions.organization_id))
    );

  // 3. Build already-processed set (expiration records that exist)
  const processedOriginalIds = new Set(
    allTransactions
      .filter(
        t =>
          t.original_transaction_id != null &&
          (t.credit_category === 'credits_expired' ||
            t.credit_category === 'orb_credit_expired' ||
            t.credit_category === 'orb_credit_voided')
      )
      .map(t => t.original_transaction_id)
  );

  // 4. Build simulation input: existing unprocessed expiring credits + modified affected credits
  const existingExpiring: ExpiringTransaction[] = allTransactions
    .filter(
      t => t.expiry_date != null && t.amount_microdollars > 0 && !processedOriginalIds.has(t.id)
    )
    .map(t => ({
      id: t.id,
      amount_microdollars: t.amount_microdollars,
      expiration_baseline_microdollars_used: t.expiration_baseline_microdollars_used,
      expiry_date: t.expiry_date,
      description: t.description,
      is_free: t.is_free,
    }));

  // Resolve per-credit expiry dates from lookup
  const modifiedAffected: ExpiringTransaction[] = affectedCredits.map(t => {
    const resolved = resolveCreditOrThrow(lookup, t.credit_category ?? '', t.description);
    const expiryDateIso = resolved.expiryDateIso;
    return {
      id: t.id,
      amount_microdollars: t.amount_microdollars,
      expiration_baseline_microdollars_used: t.original_baseline_microdollars_used ?? 0,
      expiry_date: expiryDateIso,
      description: t.description,
      is_free: t.is_free,
    };
  });

  const simulationInput = [...existingExpiring, ...modifiedAffected];

  // 5. Run simulation — use the latest expiry date among modifiedAffected as `now`
  //    to project what would happen at expiry
  const entity = { id: user.id, microdollars_used: user.microdollars_used };
  const latestExpiry = modifiedAffected.reduce<Date>((latest, t) => {
    const d = new Date(t.expiry_date as string);
    return d > latest ? d : latest;
  }, new Date(0));
  const simulationNow = latestExpiry.getTime() > 0 ? latestExpiry : new Date();
  const { newTransactions } = computeExpiration(simulationInput, entity, simulationNow, user.id);

  // 6. Map projected expired amounts back to affected credits
  const expiredByOriginalId = new Map(
    newTransactions.map(t => [t.original_transaction_id, Math.abs(t.amount_microdollars ?? 0)])
  );

  const currentBalance = user.total_microdollars_acquired - user.microdollars_used;

  // 5a. Floor at zero: if setting expiry on these credits would push the user's
  //     balance negative (e.g. because Orb already clawed back spend via
  //     total_microdollars_acquired adjustments), skip them — don't set expiry.
  //     The credits are effectively already consumed from a balance perspective.
  const existingExpiredTotal = existingExpiring.reduce((sum, t) => {
    return sum + (expiredByOriginalId.get(t.id) ?? 0);
  }, 0);
  const headroom = currentBalance - existingExpiredTotal;
  // Determine which affected credits to actually tag with expiry.
  // Sort by expiry date ascending so earlier-expiring credits are consumed first
  // when headroom is limited. Tie-break by id for determinism.
  const sortedAffected = [...affectedCredits].sort((a, b) => {
    const aExpiry = resolveCreditOrThrow(
      lookup,
      a.credit_category ?? '',
      a.description
    ).expiryDateIso;
    const bExpiry = resolveCreditOrThrow(
      lookup,
      b.credit_category ?? '',
      b.description
    ).expiryDateIso;
    if (aExpiry !== bExpiry) return aExpiry < bExpiry ? -1 : 1;
    return a.id < b.id ? -1 : 1;
  });
  // Walk credits in order; include each one as long as it fits within headroom.
  let remainingHeadroom = headroom;
  const creditsToExpire: typeof affectedCredits = [];
  const creditsSkipped: typeof affectedCredits = [];
  for (const credit of sortedAffected) {
    const expiredAmt = expiredByOriginalId.get(credit.id) ?? 0;
    if (remainingHeadroom >= expiredAmt) {
      remainingHeadroom -= expiredAmt;
      creditsToExpire.push(credit);
    } else {
      creditsSkipped.push(credit);
    }
  }

  const creditsAffectedWithProjection = affectedCredits.map(t => ({
    ...t,
    projected_expired_amount_microdollars: expiredByOriginalId.get(t.id) ?? 0,
  }));

  const projectedNoScript = currentBalance - existingExpiredTotal;
  const scriptExpiredTotal = creditsToExpire.reduce(
    (sum, t) => sum + (expiredByOriginalId.get(t.id) ?? 0),
    0
  );
  const projectedAfterScript = projectedNoScript - scriptExpiredTotal;

  // 7. Write JSONL line
  const logLine = JSON.stringify({
    user_id: user.id,
    next_credit_expiration_at: user.next_credit_expiration_at,
    current_balance_microdollars: currentBalance,
    projected_no_script_microdollars: projectedNoScript,
    projected_after_script_microdollars: projectedAfterScript,
    credits_affected: creditsAffectedWithProjection,
    credits_skipped: creditsSkipped.length > 0 ? creditsSkipped.map(c => c.id) : undefined,
  });
  output.write(logLine + '\n');

  // 8. Execute mode: write DB changes (only for credits that fit within headroom)
  if (execute && creditsToExpire.length > 0) {
    // Find earliest expiry date among credits to expire
    const earliestExpiry = creditsToExpire.reduce<string>((earliest, credit) => {
      const resolved = resolveCreditOrThrow(
        lookup,
        credit.credit_category ?? '',
        credit.description
      );
      return earliest === '' || resolved.expiryDateIso < earliest
        ? resolved.expiryDateIso
        : earliest;
    }, '');

    await db.transaction(async tx => {
      // Update each credit individually with its own expiry date
      for (const credit of creditsToExpire) {
        const resolved = resolveCreditOrThrow(
          lookup,
          credit.credit_category ?? '',
          credit.description
        );
        await tx
          .update(credit_transactions)
          .set({
            expiry_date: resolved.expiryDateIso,
            expiration_baseline_microdollars_used: sql`COALESCE(${credit_transactions.original_baseline_microdollars_used}, 0)`,
          })
          .where(eq(credit_transactions.id, credit.id));
      }

      // COALESCE needed because LEAST(NULL, x) returns NULL in PostgreSQL
      await tx
        .update(kilocode_users)
        .set({
          next_credit_expiration_at: sql`COALESCE(LEAST(${kilocode_users.next_credit_expiration_at}, ${earliestExpiry}), ${earliestExpiry})`,
        })
        .where(eq(kilocode_users.id, user.id));
    });
  }

  // 9. Log mutations (both dry run and execute — after commit in execute mode
  //    so rollbacks don't leave phantom entries)
  if (creditsToExpire.length > 0) {
    // Find earliest expiry for user record log
    const earliestExpiryForLog = creditsToExpire.reduce<string>((earliest, credit) => {
      const resolved = resolveCreditOrThrow(
        lookup,
        credit.credit_category ?? '',
        credit.description
      );
      return earliest === '' || resolved.expiryDateIso < earliest
        ? resolved.expiryDateIso
        : earliest;
    }, '');

    for (const credit of creditsToExpire) {
      const resolved = resolveCreditOrThrow(
        lookup,
        credit.credit_category ?? '',
        credit.description
      );
      mutationLog.write(
        JSON.stringify({
          type: 'credit_transaction',
          id: credit.id,
          user_id: userId,
          old: {
            expiry_date: credit.expiry_date,
            expiration_baseline_microdollars_used: credit.expiration_baseline_microdollars_used,
          },
          new: {
            expiry_date: resolved.expiryDateIso,
            expiration_baseline_microdollars_used: credit.original_baseline_microdollars_used ?? 0,
          },
        }) + '\n'
      );
    }
    mutationLog.write(
      JSON.stringify({
        type: 'kilocode_user',
        id: userId,
        old: {
          next_credit_expiration_at: user.next_credit_expiration_at,
        },
        new: {
          next_credit_expiration_at_input: earliestExpiryForLog,
        },
      }) + '\n'
    );
  }

  // 9. Return total projected expiration only for the credits we actually tagged
  const projectedExpirationForExpired = creditsToExpire.reduce(
    (sum, t) => sum + (expiredByOriginalId.get(t.id) ?? 0),
    0
  );

  return {
    creditsAffected: creditsToExpire.length,
    creditsSkipped: creditsSkipped.length,
    projectedExpiration: projectedExpirationForExpired,
  };
}

// ── Main ─────────────────────────────────────────────────────────────────────

async function main() {
  const { execute, yes, batchSize, concurrency, input } = parseArgs();
  const { rows, lookup, categoriesToQuery } = parseCsv(input);

  const trueRows = rows.filter(r => r.shouldExpire);

  console.log(`Mode: ${execute ? 'EXECUTE' : 'DRY RUN'}`);
  console.log(`Input file:  ${input}`);
  console.log(`Total rows:  ${rows.length}`);
  console.log(`TRUE rows:   ${trueRows.length}`);
  console.log(`Categories to query: ${categoriesToQuery.join(', ')}`);
  console.log(`Batch size:  ${batchSize}`);
  console.log(`Concurrency: ${concurrency}\n`);

  console.log('Rows to expire:');
  for (const row of trueRows) {
    const rowLookup = lookup.get(pairKey(row.category, row.description));
    console.log(
      `  ${row.category} | ${row.description ?? '(any)'}  [expire_in_days=${row.expireInDays}, expiry=${rowLookup?.expiryDateIso ?? '?'}]`
    );
  }
  console.log();

  // Show DB target and ask for confirmation
  const dbUrl = process.env.POSTGRES_SCRIPT_URL ?? process.env.POSTGRES_URL ?? '(unknown)';
  const dbHost = (() => {
    try {
      return new URL(dbUrl).hostname;
    } catch {
      return dbUrl;
    }
  })();
  console.log(`Database: ${dbHost}`);
  if (!yes) {
    const rl = createInterface({ input: process.stdin, output: process.stdout });
    const answer = await new Promise<string>(resolve => {
      rl.question(`\nProceed? (y/N) `, resolve);
    });
    rl.close();
    if (answer.trim().toLowerCase() !== 'y') {
      console.log('Aborted.');
      return;
    }
  }
  console.log();

  const outputDir = path.join(__dirname, 'output');
  await mkdir(outputDir, { recursive: true });
  const timestamp = new Date().toISOString().replace(/:/g, '-');
  const outputFile = `expire-free-credits-${timestamp}.jsonl`;
  const errorsFile = `expire-free-credits-${timestamp}.errors.jsonl`;
  const mutationsFile = `expire-free-credits-${timestamp}.mutations.jsonl`;
  const output = createWriteStream(path.join(outputDir, outputFile));
  const errorLog = createWriteStream(path.join(outputDir, errorsFile));
  const mutationLog = createWriteStream(path.join(outputDir, mutationsFile));
  console.log(`Output:     ${path.join(outputDir, outputFile)}`);
  console.log(`Mutations:  ${path.join(outputDir, mutationsFile)}`);
  console.log(`Errors:     ${path.join(outputDir, errorsFile)}\n`);

  const limit = pLimit(concurrency);

  // Per-(category, description) stats
  const pairStats = new Map<
    PairKey,
    { credits: number; amount: number; projectedExpiration: number }
  >();
  for (const row of rows) {
    pairStats.set(pairKey(row.category, row.description), {
      credits: 0,
      amount: 0,
      projectedExpiration: 0,
    });
  }

  let lastUserId = '';
  let totalCredits = 0;
  let totalCreditsSkipped = 0;
  let totalProjectedExpiration = 0;
  let usersProcessed = 0;
  let totalErrors = 0;

  const baseFilter = and(
    inArray(credit_transactions.credit_category, categoriesToQuery),
    eq(credit_transactions.is_free, true),
    isNull(credit_transactions.expiry_date),
    isNull(credit_transactions.organization_id)
  );

  while (true) {
    // Fetch all matching credits for the next batch of users in one query.
    // The subquery selects the next N distinct user IDs; the outer query
    // fetches every matching credit row for those users.
    const userIdSubquery = db
      .selectDistinct({ kilo_user_id: credit_transactions.kilo_user_id })
      .from(credit_transactions)
      .where(and(baseFilter, gt(credit_transactions.kilo_user_id, lastUserId)))
      .orderBy(credit_transactions.kilo_user_id)
      .limit(batchSize);

    const rawBatch = await db
      .select()
      .from(credit_transactions)
      .where(and(baseFilter, inArray(credit_transactions.kilo_user_id, userIdSubquery)));

    if (rawBatch.length === 0) break;

    // App-side filtering: only keep credits where resolveCredit returns shouldExpire=true
    const batch = rawBatch.filter(credit => {
      const resolved = resolveCredit(lookup, credit.credit_category ?? '', credit.description);
      return resolved?.shouldExpire === true;
    });

    if (batch.length === 0) {
      // Advance cursor using the raw batch to avoid infinite loop
      lastUserId = [...new Set(rawBatch.map(c => c.kilo_user_id))].sort().pop() ?? lastUserId;
      continue;
    }

    totalCredits += batch.length;

    // Track per-pair stats from filtered batch
    for (const credit of batch) {
      const specificKey = pairKey(credit.credit_category ?? '', credit.description);
      const anyKey = pairKey(credit.credit_category ?? '', null);
      const stats = pairStats.get(specificKey) ?? pairStats.get(anyKey);
      if (stats) {
        stats.credits++;
        stats.amount += credit.amount_microdollars;
      }
    }

    // Group by user
    const byUser = new Map<string, typeof batch>();
    for (const credit of batch) {
      const existing = byUser.get(credit.kilo_user_id);
      if (existing) {
        existing.push(credit);
      } else {
        byUser.set(credit.kilo_user_id, [credit]);
      }
    }

    const results = await Promise.allSettled(
      [...byUser.entries()].map(([userId, credits]) =>
        limit(async () => {
          const result = await processUser(userId, credits, execute, output, mutationLog, lookup);
          return { userId, result };
        })
      )
    );

    for (const settled of results) {
      if (settled.status === 'rejected') {
        totalErrors++;
        const error =
          settled.reason instanceof Error ? settled.reason.message : String(settled.reason);
        errorLog.write(JSON.stringify({ error }) + '\n');
      } else {
        usersProcessed++;
        totalProjectedExpiration += settled.value.result.projectedExpiration;
        totalCreditsSkipped += settled.value.result.creditsSkipped;
      }
    }

    lastUserId = [...new Set(rawBatch.map(c => c.kilo_user_id))].sort().pop() ?? lastUserId;
    console.log(
      `  ${totalCredits} credits fetched, ${usersProcessed} users processed, ${totalErrors} errors`
    );
  }

  output.end();
  errorLog.end();
  mutationLog.end();

  const fmt = (microdollars: number) =>
    `$${(microdollars / 1_000_000).toLocaleString('en-US', { minimumFractionDigits: 2, maximumFractionDigits: 2 })}`;

  console.log('\n--- Per-category breakdown ---');
  for (const [key, stats] of pairStats) {
    if (stats.credits === 0) {
      console.log(`  ${key}: no matching credits found`);
    } else {
      console.log(`  ${key}: ${stats.credits} credits, ${fmt(stats.amount)} total`);
    }
  }

  console.log('\n--- Summary ---');
  console.log(
    `Total credits:               ${totalCredits} (${fmt(totalCredits > 0 ? [...pairStats.values()].reduce((s, v) => s + v.amount, 0) : 0)})`
  );
  console.log(`Users processed:             ${usersProcessed}`);
  console.log(`Credits skipped (neg bal):   ${totalCreditsSkipped}`);
  console.log(`Projected expiration:        ${fmt(totalProjectedExpiration)}`);
  console.log(`Errors:                      ${totalErrors}`);
  console.log(`Mode:                        ${execute ? 'EXECUTED' : 'DRY RUN'}`);
}

void main()
  .catch(err => {
    console.error('Fatal error:', err);
    process.exit(1);
  })
  .finally(() => closeAllDrizzleConnections());
