/**
 * Schema generator for `@kilocode/wl-sdk`.
 *
 * Reads `wasteland/schema/commons.sql` (the canonical wasteland schema) and
 * emits two TypeScript files into `src/commons/`:
 *
 *  - `schema.generated.ts` — Zod row schemas, row type aliases, table column
 *    metadata, and `COMMONS_SCHEMA_STATEMENTS` (the DDL split into individual
 *    statements, suitable for feeding into DoltHub's write API one at a time).
 *
 *  - `dml.generated.ts` — TypeScript ports of each `*DML` helper in the Go
 *    reference at `wasteland/internal/commons/commons.go`. These are NOT
 *    derived from the SQL schema; they are hand-written templates owned by
 *    this generator. When a new Go helper is added, update `DML_HELPERS`
 *    below and regenerate. Each emitted TS function produces byte-for-byte
 *    identical SQL to its Go counterpart for the same inputs.
 *
 * After writing both files, the generator shells out to `pnpm format` so the
 * output is oxfmt-clean and CI's drift check stays stable.
 *
 * Path resolution: `commons.sql` is read from
 * `${WASTELAND_REPO_PATH}/schema/commons.sql`, where `WASTELAND_REPO_PATH`
 * defaults to `../wasteland` relative to the cloud repo root. Override the
 * env var when the wasteland repo lives elsewhere.
 *
 * To regenerate manually: `pnpm --filter @kilocode/wl-sdk generate`
 */

import { execSync } from 'node:child_process';
import { createHash } from 'node:crypto';
import { readFileSync, writeFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

import { parseSchema, type ColumnType, type ParsedColumn, type ParsedTable } from './sql-parser';

const __dirname = dirname(fileURLToPath(import.meta.url));
const PACKAGE_ROOT = resolve(__dirname, '..');
const CLOUD_ROOT = resolve(PACKAGE_ROOT, '..', '..');
const WASTELAND_REPO_PATH =
  process.env.WASTELAND_REPO_PATH ?? resolve(CLOUD_ROOT, '..', 'wasteland');
const SCHEMA_PATH = resolve(WASTELAND_REPO_PATH, 'schema', 'commons.sql');
const OUT_SCHEMA = resolve(PACKAGE_ROOT, 'src', 'commons', 'schema.generated.ts');
const OUT_DML = resolve(PACKAGE_ROOT, 'src', 'commons', 'dml.generated.ts');

const HEADER_LINES = [
  '// AUTO-GENERATED. Do not edit by hand.',
  '// Source: wasteland/schema/commons.sql',
  '// Generated by: packages/wl-sdk/scripts/generate-from-schema.ts',
  '// To regenerate: pnpm --filter @kilocode/wl-sdk generate',
];

function pascalCase(snake: string): string {
  return snake
    .split('_')
    .filter(p => p.length > 0)
    .map(p => p[0].toUpperCase() + p.slice(1))
    .join('');
}

function camelCase(snake: string): string {
  const pascal = pascalCase(snake);
  return pascal[0].toLowerCase() + pascal.slice(1);
}

/**
 * Map a parsed SQL column type to a Zod expression. The result is a string
 * like `z.string()` or `z.number().int()` — without the trailing
 * `.nullable()`, which is appended by the caller based on `notNull`.
 */
function zodForColumnType(type: ColumnType): string {
  switch (type.kind) {
    case 'varchar':
    case 'text':
      return 'z.string()';
    case 'int':
      return 'z.number().int()';
    case 'tinyint':
      // TINYINT(1) is the MySQL boolean idiom, but DoltHub returns it as a
      // numeric string/number. Keep it as `number` to match how the existing
      // `services/wasteland` code handles it.
      return 'z.number().int()';
    case 'float':
      return 'z.number()';
    case 'json':
      return 'z.unknown()';
    case 'timestamp':
    case 'datetime':
      // DoltHub returns timestamps as strings (e.g. `2025-01-02 15:04:05`),
      // not RFC3339, so we don't use `.datetime()`.
      return 'z.string()';
    case 'unknown':
      return 'z.unknown()';
  }
}

function renderColumnZod(col: ParsedColumn): string {
  const base = zodForColumnType(col.type);
  return col.notNull ? base : `${base}.nullable()`;
}

function renderRowSchema(table: ParsedTable): string {
  const lines = table.columns.map(col => {
    const key = /^[A-Za-z_][A-Za-z0-9_]*$/.test(col.name) ? col.name : JSON.stringify(col.name);
    return `  ${key}: ${renderColumnZod(col)},`;
  });
  const schemaName = `${pascalCase(table.name)}RowSchema`;
  return [
    `export const ${schemaName} = z.object({`,
    ...lines,
    '});',
    '',
    `export type ${pascalCase(table.name)}Row = z.infer<typeof ${schemaName}>;`,
  ].join('\n');
}

function renderTableMeta(table: ParsedTable): string {
  const constName = `${camelCase(table.name)}Table`;
  const cols = table.columns.map(c => JSON.stringify(c.name)).join(', ');
  const pk = table.primaryKey ? JSON.stringify(table.primaryKey) : 'null';
  return [
    `export const ${constName} = {`,
    `  name: ${JSON.stringify(table.name)},`,
    `  columns: [${cols}] as const,`,
    `  primaryKey: ${pk},`,
    `} as const;`,
  ].join('\n');
}

/**
 * Re-emit the original DDL for a single table so that the resulting string
 * matches the source file's wording. We re-indent the body to two spaces,
 * matching the existing `services/wasteland/src/upstream-bootstrap/commons-schema.ts`.
 */
function renderCreateTableStatement(rawDdl: string): string {
  // Normalise leading whitespace inside parens to 4-space indent, matching
  // the existing hand-written commons-schema.ts. We keep the original
  // wording inside the parentheses.
  return rawDdl.trim();
}

function renderSchemaStatements(statements: string[]): string {
  const items = statements
    .map(stmt => {
      // Use template literals so backticks get escaped, single quotes stay
      // literal, and the multi-line shape is preserved.
      const escaped = stmt.replace(/\\/g, '\\\\').replace(/`/g, '\\`').replace(/\$\{/g, '\\${');
      return `  \`${escaped}\`,`;
    })
    .join('\n\n');
  return `export const COMMONS_SCHEMA_STATEMENTS: readonly string[] = [\n${items}\n];`;
}

function emitSchemaFile(schemaSql: string): string {
  const parsed = parseSchema(schemaSql);

  const versionStmt = parsed.statements.find(s =>
    /INSERT\s+IGNORE\s+INTO\s+_meta.+schema_version/i.test(s)
  );
  const versionMatch = versionStmt
    ? /VALUES\s*\(\s*'schema_version'\s*,\s*'([^']+)'/i.exec(versionStmt)
    : null;
  const schemaVersion = versionMatch ? versionMatch[1] : 'unknown';

  const sections: string[] = [];
  sections.push(HEADER_LINES.join('\n'));
  sections.push(`import { z } from 'zod';`);
  sections.push(`export const COMMONS_SCHEMA_VERSION = ${JSON.stringify(schemaVersion)} as const;`);

  for (const table of parsed.tables) {
    sections.push(renderRowSchema(table));
    sections.push(renderTableMeta(table));
  }

  sections.push(
    [
      '/**',
      ' * The wasteland commons DDL split into individual statements, ready to',
      " * feed to DoltHub's write API one at a time. Order is preserved from",
      ' * the source file. Statements have no trailing `;` so callers can append',
      ' * one (or not) as the API expects.',
      ' */',
      renderSchemaStatements(parsed.statements.map(renderCreateTableStatement)),
    ].join('\n')
  );

  return sections.join('\n\n') + '\n';
}

// ---------------------------------------------------------------------------
// DML helpers
// ---------------------------------------------------------------------------

/**
 * Each entry is the raw TypeScript source for one generated DML helper.
 * These templates are hand-written ports of the `*DML` functions in the Go
 * reference at `wasteland/internal/commons/commons.go`. The generator owns
 * them (they are not derived from SQL); when a new Go helper is added,
 * append an entry here and regenerate.
 *
 * The helpers below depend on `escapeSqlString`, `sqlStringOrNull`, and
 * `sqlValue` from `./escape`, plus `formatTagsJson` defined locally in the
 * generated file. They produce byte-for-byte identical SQL to their Go
 * counterparts for the same inputs.
 */
const DML_HELPERS: ReadonlyArray<{ name: string; goRef: string; source: string }> = [
  {
    name: 'insertWantedDML',
    goRef: 'InsertWantedDML (commons.go:276)',
    source: `
export type InsertWantedInput = {
  id: string;
  title: string;
  description?: string;
  project?: string;
  type?: string;
  /**
   * Priority value emitted verbatim into the INSERT. Defaults to \`0\` to
   * match the Go reference, where \`item.Priority\` is the int zero-value
   * when unset. Note: the DB schema declares \`priority INT DEFAULT 2\`,
   * but the DML always writes an explicit value, so the DB default never
   * applies here.
   */
  priority?: number;
  tags?: readonly string[];
  postedBy?: string;
  status?: string;
  effortLevel?: string;
  /** UTC timestamp formatted as 'YYYY-MM-DD HH:MM:SS'. Defaults to now. */
  now?: string;
};

/**
 * Port of \`InsertWantedDML\` (commons.go:276). Validates required fields
 * (id, title) and returns a single multi-row INSERT statement.
 */
export function insertWantedDML(input: InsertWantedInput): string {
  if (input.id === '') throw new Error('wanted item ID cannot be empty');
  if (input.title === '') throw new Error('wanted item title cannot be empty');

  const now = input.now ?? formatNowUtc(new Date());
  const tagsJson = formatTagsJson(input.tags);

  const descField = sqlStringOrNull(input.description);
  const projectField = sqlStringOrNull(input.project);
  const typeField = sqlStringOrNull(input.type);
  const postedByField = sqlStringOrNull(input.postedBy);
  const effortField = input.effortLevel && input.effortLevel !== ''
    ? \`'\${escapeSqlString(input.effortLevel)}'\`
    : "'medium'";
  const status = input.status && input.status !== ''
    ? \`'\${escapeSqlString(input.status)}'\`
    : "'open'";
  const priority = input.priority ?? 0;

  return (
    \`INSERT INTO wanted (id, title, description, project, type, priority, tags, posted_by, status, effort_level, created_at, updated_at)\\n\` +
    \`VALUES ('\${escapeSqlString(input.id)}', '\${escapeSqlString(input.title)}', \${descField}, \${projectField}, \${typeField}, \${priority}, \${tagsJson}, \${postedByField}, \${status}, \${effortField}, '\${now}', '\${now}')\`
  );
}
`.trim(),
  },
  {
    name: 'claimWantedDML',
    goRef: 'ClaimWantedDML (commons.go:329)',
    source: `
export type ClaimWantedInput = {
  wantedId: string;
  rigHandle: string;
};

/** Port of \`ClaimWantedDML\` (commons.go:329). */
export function claimWantedDML(input: ClaimWantedInput): string {
  return (
    \`UPDATE wanted SET claimed_by='\${escapeSqlString(input.rigHandle)}', \` +
    \`status='claimed', updated_at=NOW() WHERE id='\${escapeSqlString(input.wantedId)}' \` +
    \`AND status='open'\`
  );
}
`.trim(),
  },
  {
    name: 'unclaimWantedDML',
    goRef: 'UnclaimWantedDML (commons.go:347)',
    source: `
export type UnclaimWantedInput = {
  wantedId: string;
};

/** Port of \`UnclaimWantedDML\` (commons.go:347). */
export function unclaimWantedDML(input: UnclaimWantedInput): string {
  return (
    \`UPDATE wanted SET claimed_by=NULL, status='open', updated_at=NOW() \` +
    \`WHERE id='\${escapeSqlString(input.wantedId)}' AND status='claimed'\`
  );
}
`.trim(),
  },
  {
    name: 'submitCompletionDML',
    goRef: 'SubmitCompletionDML (commons.go:365)',
    source: `
export type SubmitCompletionInput = {
  completionId: string;
  wantedId: string;
  rigHandle: string;
  evidence: string;
  hopUri?: string;
};

/**
 * Port of \`SubmitCompletionDML\` (commons.go:365). Returns two statements:
 * an UPDATE on \`wanted\` followed by an INSERT IGNORE on \`completions\`.
 */
export function submitCompletionDML(input: SubmitCompletionInput): string[] {
  const hopField = sqlStringOrNull(input.hopUri);

  const update =
    \`UPDATE wanted SET status='in_review', evidence_url='\${escapeSqlString(input.evidence)}', \` +
    \`updated_at=NOW() WHERE id='\${escapeSqlString(input.wantedId)}' \` +
    \`AND status='claimed' AND claimed_by='\${escapeSqlString(input.rigHandle)}'\`;

  const insert =
    \`INSERT IGNORE INTO completions (id, wanted_id, completed_by, evidence, hop_uri, completed_at) \` +
    \`SELECT '\${escapeSqlString(input.completionId)}', '\${escapeSqlString(input.wantedId)}', \` +
    \`'\${escapeSqlString(input.rigHandle)}', '\${escapeSqlString(input.evidence)}', \${hopField}, NOW() \` +
    \`FROM wanted WHERE id='\${escapeSqlString(input.wantedId)}' AND status='in_review' \` +
    \`AND claimed_by='\${escapeSqlString(input.rigHandle)}' \` +
    \`AND NOT EXISTS (SELECT 1 FROM completions WHERE wanted_id='\${escapeSqlString(input.wantedId)}')\`;

  return [update, insert];
}
`.trim(),
  },
  {
    name: 'acceptCompletionDML',
    goRef: 'AcceptCompletionDML (commons.go:680)',
    source: `
export type StampInput = {
  id: string;
  subject: string;
  quality: number;
  reliability: number;
  severity: string;
  skillTags?: readonly string[];
  message?: string;
};

export type AcceptCompletionInput = {
  wantedId: string;
  completionId: string;
  rigHandle: string;
  hopUri?: string;
  stamp: StampInput;
};

/**
 * Port of \`AcceptCompletionDML\` (commons.go:680). Returns three statements:
 * INSERT stamp, UPDATE completion, UPDATE wanted.
 */
export function acceptCompletionDML(input: AcceptCompletionInput): string[] {
  const tagsField = formatTagsJson(input.stamp.skillTags);
  const msgField = sqlStringOrNull(input.stamp.message);
  const hopField = sqlStringOrNull(input.hopUri);

  const valence = \`{"quality": \${input.stamp.quality}, "reliability": \${input.stamp.reliability}}\`;

  const insertStamp =
    \`INSERT INTO stamps (id, author, subject, valence, confidence, severity, context_id, context_type, skill_tags, message, hop_uri, created_at) \` +
    \`VALUES ('\${escapeSqlString(input.stamp.id)}', '\${escapeSqlString(input.rigHandle)}', \` +
    \`'\${escapeSqlString(input.stamp.subject)}', '\${escapeSqlString(valence)}', 1.0, \` +
    \`'\${escapeSqlString(input.stamp.severity)}', '\${escapeSqlString(input.completionId)}', 'completion', \` +
    \`\${tagsField}, \${msgField}, \${hopField}, NOW())\`;

  const updateCompletion =
    \`UPDATE completions SET validated_by='\${escapeSqlString(input.rigHandle)}', \` +
    \`stamp_id='\${escapeSqlString(input.stamp.id)}', validated_at=NOW() \` +
    \`WHERE id='\${escapeSqlString(input.completionId)}'\`;

  const updateWanted =
    \`UPDATE wanted SET status='completed', updated_at=NOW() \` +
    \`WHERE id='\${escapeSqlString(input.wantedId)}' AND status='in_review'\`;

  return [insertStamp, updateCompletion, updateWanted];
}
`.trim(),
  },
  {
    name: 'acceptUpstreamDML',
    goRef: 'AcceptUpstreamDML (commons.go:713)',
    source: `
export type AcceptUpstreamInput = {
  wantedId: string;
  completionId: string;
  completedBy: string;
  evidence: string;
  rigHandle: string;
  hopUri?: string;
  stamp: StampInput;
};

/**
 * Port of \`AcceptUpstreamDML\` (commons.go:713). Atomically adopts a fork's
 * completion onto the upstream branch: DELETE existing completion, INSERT
 * fork completion, UPDATE wanted, INSERT stamp, UPDATE completion w/ stamp ref.
 */
export function acceptUpstreamDML(input: AcceptUpstreamInput): string[] {
  const tagsField = formatTagsJson(input.stamp.skillTags);
  const msgField = sqlStringOrNull(input.stamp.message);
  const hopField = sqlStringOrNull(input.hopUri);

  const valence = \`{"quality": \${input.stamp.quality}, "reliability": \${input.stamp.reliability}}\`;

  const deleteCompletion = \`DELETE FROM completions WHERE wanted_id='\${escapeSqlString(input.wantedId)}'\`;

  const insertCompletion =
    \`INSERT IGNORE INTO completions (id, wanted_id, completed_by, evidence, hop_uri, completed_at) \` +
    \`VALUES ('\${escapeSqlString(input.completionId)}', '\${escapeSqlString(input.wantedId)}', \` +
    \`'\${escapeSqlString(input.completedBy)}', '\${escapeSqlString(input.evidence)}', \${hopField}, NOW())\`;

  const updateWanted =
    \`UPDATE wanted SET status='completed', claimed_by='\${escapeSqlString(input.completedBy)}', \` +
    \`evidence_url='\${escapeSqlString(input.evidence)}', updated_at=NOW() \` +
    \`WHERE id='\${escapeSqlString(input.wantedId)}'\`;

  const insertStamp =
    \`INSERT INTO stamps (id, author, subject, valence, confidence, severity, context_id, context_type, skill_tags, message, hop_uri, created_at) \` +
    \`VALUES ('\${escapeSqlString(input.stamp.id)}', '\${escapeSqlString(input.rigHandle)}', \` +
    \`'\${escapeSqlString(input.stamp.subject)}', '\${escapeSqlString(valence)}', 1.0, \` +
    \`'\${escapeSqlString(input.stamp.severity)}', '\${escapeSqlString(input.completionId)}', 'completion', \` +
    \`\${tagsField}, \${msgField}, \${hopField}, NOW())\`;

  const updateCompletion =
    \`UPDATE completions SET validated_by='\${escapeSqlString(input.rigHandle)}', \` +
    \`stamp_id='\${escapeSqlString(input.stamp.id)}', validated_at=NOW() \` +
    \`WHERE id='\${escapeSqlString(input.completionId)}'\`;

  return [deleteCompletion, insertCompletion, updateWanted, insertStamp, updateCompletion];
}
`.trim(),
  },
  {
    name: 'closeUpstreamDML',
    goRef: 'CloseUpstreamDML (commons.go:751)',
    source: `
export type CloseUpstreamInput = {
  wantedId: string;
  completionId: string;
  completedBy: string;
  evidence: string;
  hopUri?: string;
};

/**
 * Port of \`CloseUpstreamDML\` (commons.go:751). Adopts a fork submission
 * without creating a stamp.
 */
export function closeUpstreamDML(input: CloseUpstreamInput): string[] {
  const hopField = sqlStringOrNull(input.hopUri);

  const deleteCompletion = \`DELETE FROM completions WHERE wanted_id='\${escapeSqlString(input.wantedId)}'\`;

  const insertCompletion =
    \`INSERT IGNORE INTO completions (id, wanted_id, completed_by, evidence, hop_uri, completed_at) \` +
    \`VALUES ('\${escapeSqlString(input.completionId)}', '\${escapeSqlString(input.wantedId)}', \` +
    \`'\${escapeSqlString(input.completedBy)}', '\${escapeSqlString(input.evidence)}', \${hopField}, NOW())\`;

  const updateWanted =
    \`UPDATE wanted SET status='completed', claimed_by='\${escapeSqlString(input.completedBy)}', \` +
    \`evidence_url='\${escapeSqlString(input.evidence)}', updated_at=NOW() \` +
    \`WHERE id='\${escapeSqlString(input.wantedId)}'\`;

  return [deleteCompletion, insertCompletion, updateWanted];
}
`.trim(),
  },
  {
    name: 'updateWantedDML',
    goRef: 'UpdateWantedDML (commons.go:783)',
    source: `
export type WantedUpdateFields = {
  title?: string;
  description?: string;
  project?: string;
  type?: string;
  /** Use undefined or a negative number to leave priority unchanged. */
  priority?: number;
  effortLevel?: string;
  /** Set tags to a (possibly empty) array to update; leave undefined to skip. */
  tags?: readonly string[];
};

export type UpdateWantedInput = {
  wantedId: string;
  fields: WantedUpdateFields;
};

/**
 * Port of \`UpdateWantedDML\` (commons.go:783). Builds a partial UPDATE.
 * Throws if no fields are provided. The Go reference uses zero-values to mean
 * "not set"; we match that: empty strings, undefined, and negative priorities
 * are skipped. \`tags\` being present (even an empty array) marks it as set.
 */
export function updateWantedDML(input: UpdateWantedInput): string {
  const setClauses: string[] = [];
  const f = input.fields;

  if (f.title !== undefined && f.title !== '') {
    setClauses.push(\`title='\${escapeSqlString(f.title)}'\`);
  }
  if (f.description !== undefined && f.description !== '') {
    setClauses.push(\`description='\${escapeSqlString(f.description)}'\`);
  }
  if (f.project !== undefined && f.project !== '') {
    setClauses.push(\`project='\${escapeSqlString(f.project)}'\`);
  }
  if (f.type !== undefined && f.type !== '') {
    setClauses.push(\`type='\${escapeSqlString(f.type)}'\`);
  }
  if (f.priority !== undefined && f.priority >= 0) {
    setClauses.push(\`priority=\${f.priority}\`);
  }
  if (f.effortLevel !== undefined && f.effortLevel !== '') {
    setClauses.push(\`effort_level='\${escapeSqlString(f.effortLevel)}'\`);
  }
  if (f.tags !== undefined) {
    setClauses.push(\`tags=\${formatTagsJson(f.tags)}\`);
  }

  if (setClauses.length === 0) {
    throw new Error('no fields to update');
  }

  setClauses.push('updated_at=NOW()');

  return \`UPDATE wanted SET \${setClauses.join(', ')} WHERE id='\${escapeSqlString(input.wantedId)}' AND status='open'\`;
}
`.trim(),
  },
  {
    name: 'closeWantedDML',
    goRef: 'CloseWantedDML (commons.go:836)',
    source: `
export type CloseWantedInput = {
  wantedId: string;
};

/** Port of \`CloseWantedDML\` (commons.go:836). */
export function closeWantedDML(input: CloseWantedInput): string {
  return (
    \`UPDATE wanted SET status='completed', updated_at=NOW() \` +
    \`WHERE id='\${escapeSqlString(input.wantedId)}' AND status='in_review'\`
  );
}
`.trim(),
  },
  {
    name: 'deleteWantedDML',
    goRef: 'DeleteWantedDML (commons.go:869)',
    source: `
export type DeleteWantedInput = {
  wantedId: string;
};

/** Port of \`DeleteWantedDML\` (commons.go:869). Soft-delete via status='withdrawn'. */
export function deleteWantedDML(input: DeleteWantedInput): string {
  return (
    \`UPDATE wanted SET status='withdrawn', updated_at=NOW() \` +
    \`WHERE id='\${escapeSqlString(input.wantedId)}' AND status='open'\`
  );
}
`.trim(),
  },
  {
    name: 'rejectCompletionDML',
    goRef: 'RejectCompletionDML (commons.go:887)',
    source: `
export type RejectCompletionInput = {
  wantedId: string;
};

/** Port of \`RejectCompletionDML\` (commons.go:887). Returns DELETE + UPDATE. */
export function rejectCompletionDML(input: RejectCompletionInput): string[] {
  const wantedId = escapeSqlString(input.wantedId);
  return [
    \`DELETE FROM completions WHERE wanted_id='\${wantedId}'\`,
    \`UPDATE wanted SET status='claimed', updated_at=NOW() WHERE id='\${wantedId}' AND status='in_review'\`,
  ];
}
`.trim(),
  },
];

const DML_SHARED_HELPERS = `
/**
 * Format a string array as a JSON array SQL literal, mirroring Go's
 * \`formatTagsJSON\` (commons.go:854). Empty/undefined arrays return the
 * literal \`NULL\`. Backslashes and double quotes inside tags are escaped.
 */
export function formatTagsJson(tags: readonly string[] | undefined): string {
  if (!tags || tags.length === 0) return 'NULL';
  const escaped = tags.map(t => t.replace(/\\\\/g, '\\\\\\\\').replace(/"/g, '\\\\"'));
  const jsonStr = \`["\${escaped.join('","')}"]\`;
  return \`'\${jsonStr.replace(/'/g, "''")}'\`;
}

/**
 * Format a Date as the UTC string \`YYYY-MM-DD HH:MM:SS\` used by the Go
 * reference for \`created_at\` / \`updated_at\` literals.
 */
export function formatNowUtc(d: Date): string {
  const pad = (n: number): string => n.toString().padStart(2, '0');
  return (
    \`\${d.getUTCFullYear()}-\${pad(d.getUTCMonth() + 1)}-\${pad(d.getUTCDate())} \` +
    \`\${pad(d.getUTCHours())}:\${pad(d.getUTCMinutes())}:\${pad(d.getUTCSeconds())}\`
  );
}
`.trim();

function emitDmlFile(): string {
  const sections: string[] = [];
  sections.push(HEADER_LINES.join('\n'));
  sections.push(`import { escapeSqlString, sqlStringOrNull } from './escape';`);
  sections.push(DML_SHARED_HELPERS);
  for (const helper of DML_HELPERS) {
    sections.push(`// ${helper.goRef}`);
    sections.push(helper.source);
  }
  return sections.join('\n\n') + '\n';
}

// ---------------------------------------------------------------------------
// Driver
// ---------------------------------------------------------------------------

function main(): void {
  const schemaSql = readFileSync(SCHEMA_PATH, 'utf8');
  const sha = createHash('sha256').update(schemaSql).digest('hex').slice(0, 12);

  const schemaOut = emitSchemaFile(schemaSql);
  const dmlOut = emitDmlFile();

  writeFileSync(OUT_SCHEMA, schemaOut);
  writeFileSync(OUT_DML, dmlOut);

  // Format the freshly written files in place so the committed output is
  // oxfmt-stable. The repo's `.prettierignore` excludes `*.generated.*`, so
  // we explicitly bypass it with `--ignore-path /dev/null` — we *want* these
  // files formatted so CI's drift check stays deterministic.
  try {
    execSync(`pnpm -w exec oxfmt --ignore-path /dev/null "${OUT_SCHEMA}" "${OUT_DML}"`, {
      stdio: 'inherit',
      cwd: CLOUD_ROOT,
    });
  } catch (err) {
    console.error('oxfmt failed; output written unformatted');
    throw err;
  }

  const parsed = parseSchema(schemaSql);
  console.log(
    `Generated ${parsed.tables.length} row schemas, ${DML_HELPERS.length} DML helpers from commons.sql (sha=${sha})`
  );
}

main();
