import type { GmailPushIdempotency } from './idempotency';

export interface GmailPushQueueMessage {
  userId: string;
  pubSubBody: string;
  messageId: string; // Pub/Sub message ID (idempotency key)
  attempt?: number; // retry attempt (0 = first delivery)
}

// Env is generated by `wrangler types` in worker-configuration.d.ts
// Extend here only for queue message typing
export type AppEnv = Env & {
  GMAIL_PUSH_QUEUE: Queue<GmailPushQueueMessage>;
  IDEMPOTENCY: DurableObjectNamespace<GmailPushIdempotency>;
};

export type HonoContext = {
  Bindings: AppEnv;
};
