// AUTO-GENERATED. Do not edit by hand.
// Source: wasteland/schema/commons.sql
// Generated by: packages/wl-sdk/scripts/generate-from-schema.ts
// To regenerate: pnpm --filter @kilocode/wl-sdk generate

import { escapeSqlString, sqlStringOrNull } from './escape';

/**
 * Format a string array as a JSON array SQL literal, mirroring Go's
 * `formatTagsJSON` (commons.go:854). Empty/undefined arrays return the
 * literal `NULL`. Backslashes and double quotes inside tags are escaped.
 */
export function formatTagsJson(tags: readonly string[] | undefined): string {
  if (!tags || tags.length === 0) return 'NULL';
  const escaped = tags.map(t => t.replace(/\\/g, '\\\\').replace(/"/g, '\\"'));
  const jsonStr = `["${escaped.join('","')}"]`;
  return `'${jsonStr.replace(/'/g, "''")}'`;
}

/**
 * Format a Date as the UTC string `YYYY-MM-DD HH:MM:SS` used by the Go
 * reference for `created_at` / `updated_at` literals.
 */
export function formatNowUtc(d: Date): string {
  const pad = (n: number): string => n.toString().padStart(2, '0');
  return (
    `${d.getUTCFullYear()}-${pad(d.getUTCMonth() + 1)}-${pad(d.getUTCDate())} ` +
    `${pad(d.getUTCHours())}:${pad(d.getUTCMinutes())}:${pad(d.getUTCSeconds())}`
  );
}

// InsertWantedDML (commons.go:276)

export type InsertWantedInput = {
  id: string;
  title: string;
  description?: string;
  project?: string;
  type?: string;
  /**
   * Priority value emitted verbatim into the INSERT. Defaults to `0` to
   * match the Go reference, where `item.Priority` is the int zero-value
   * when unset. Note: the DB schema declares `priority INT DEFAULT 2`,
   * but the DML always writes an explicit value, so the DB default never
   * applies here.
   */
  priority?: number;
  tags?: readonly string[];
  postedBy?: string;
  status?: string;
  effortLevel?: string;
  /** UTC timestamp formatted as 'YYYY-MM-DD HH:MM:SS'. Defaults to now. */
  now?: string;
};

/**
 * Port of `InsertWantedDML` (commons.go:276). Validates required fields
 * (id, title) and returns a single multi-row INSERT statement.
 */
export function insertWantedDML(input: InsertWantedInput): string {
  if (input.id === '') throw new Error('wanted item ID cannot be empty');
  if (input.title === '') throw new Error('wanted item title cannot be empty');

  const now = input.now ?? formatNowUtc(new Date());
  const tagsJson = formatTagsJson(input.tags);

  const descField = sqlStringOrNull(input.description);
  const projectField = sqlStringOrNull(input.project);
  const typeField = sqlStringOrNull(input.type);
  const postedByField = sqlStringOrNull(input.postedBy);
  const effortField =
    input.effortLevel && input.effortLevel !== ''
      ? `'${escapeSqlString(input.effortLevel)}'`
      : "'medium'";
  const status =
    input.status && input.status !== '' ? `'${escapeSqlString(input.status)}'` : "'open'";
  const priority = input.priority ?? 0;

  return (
    `INSERT INTO wanted (id, title, description, project, type, priority, tags, posted_by, status, effort_level, created_at, updated_at)\n` +
    `VALUES ('${escapeSqlString(input.id)}', '${escapeSqlString(input.title)}', ${descField}, ${projectField}, ${typeField}, ${priority}, ${tagsJson}, ${postedByField}, ${status}, ${effortField}, '${now}', '${now}')`
  );
}

// ClaimWantedDML (commons.go:329)

export type ClaimWantedInput = {
  wantedId: string;
  rigHandle: string;
};

/** Port of `ClaimWantedDML` (commons.go:329). */
export function claimWantedDML(input: ClaimWantedInput): string {
  return (
    `UPDATE wanted SET claimed_by='${escapeSqlString(input.rigHandle)}', ` +
    `status='claimed', updated_at=NOW() WHERE id='${escapeSqlString(input.wantedId)}' ` +
    `AND status='open'`
  );
}

// UnclaimWantedDML (commons.go:347)

export type UnclaimWantedInput = {
  wantedId: string;
};

/** Port of `UnclaimWantedDML` (commons.go:347). */
export function unclaimWantedDML(input: UnclaimWantedInput): string {
  return (
    `UPDATE wanted SET claimed_by=NULL, status='open', updated_at=NOW() ` +
    `WHERE id='${escapeSqlString(input.wantedId)}' AND status='claimed'`
  );
}

// SubmitCompletionDML (commons.go:365)

export type SubmitCompletionInput = {
  completionId: string;
  wantedId: string;
  rigHandle: string;
  evidence: string;
  hopUri?: string;
};

/**
 * Port of `SubmitCompletionDML` (commons.go:365). Returns two statements:
 * an UPDATE on `wanted` followed by an INSERT IGNORE on `completions`.
 */
export function submitCompletionDML(input: SubmitCompletionInput): string[] {
  const hopField = sqlStringOrNull(input.hopUri);

  const update =
    `UPDATE wanted SET status='in_review', evidence_url='${escapeSqlString(input.evidence)}', ` +
    `updated_at=NOW() WHERE id='${escapeSqlString(input.wantedId)}' ` +
    `AND status='claimed' AND claimed_by='${escapeSqlString(input.rigHandle)}'`;

  const insert =
    `INSERT IGNORE INTO completions (id, wanted_id, completed_by, evidence, hop_uri, completed_at) ` +
    `SELECT '${escapeSqlString(input.completionId)}', '${escapeSqlString(input.wantedId)}', ` +
    `'${escapeSqlString(input.rigHandle)}', '${escapeSqlString(input.evidence)}', ${hopField}, NOW() ` +
    `FROM wanted WHERE id='${escapeSqlString(input.wantedId)}' AND status='in_review' ` +
    `AND claimed_by='${escapeSqlString(input.rigHandle)}' ` +
    `AND NOT EXISTS (SELECT 1 FROM completions WHERE wanted_id='${escapeSqlString(input.wantedId)}')`;

  return [update, insert];
}

// AcceptCompletionDML (commons.go:680)

export type StampInput = {
  id: string;
  subject: string;
  quality: number;
  reliability: number;
  severity: string;
  skillTags?: readonly string[];
  message?: string;
};

export type AcceptCompletionInput = {
  wantedId: string;
  completionId: string;
  rigHandle: string;
  hopUri?: string;
  stamp: StampInput;
};

/**
 * Port of `AcceptCompletionDML` (commons.go:680). Returns three statements:
 * INSERT stamp, UPDATE completion, UPDATE wanted.
 */
export function acceptCompletionDML(input: AcceptCompletionInput): string[] {
  const tagsField = formatTagsJson(input.stamp.skillTags);
  const msgField = sqlStringOrNull(input.stamp.message);
  const hopField = sqlStringOrNull(input.hopUri);

  const valence = `{"quality": ${input.stamp.quality}, "reliability": ${input.stamp.reliability}}`;

  const insertStamp =
    `INSERT INTO stamps (id, author, subject, valence, confidence, severity, context_id, context_type, skill_tags, message, hop_uri, created_at) ` +
    `VALUES ('${escapeSqlString(input.stamp.id)}', '${escapeSqlString(input.rigHandle)}', ` +
    `'${escapeSqlString(input.stamp.subject)}', '${escapeSqlString(valence)}', 1.0, ` +
    `'${escapeSqlString(input.stamp.severity)}', '${escapeSqlString(input.completionId)}', 'completion', ` +
    `${tagsField}, ${msgField}, ${hopField}, NOW())`;

  const updateCompletion =
    `UPDATE completions SET validated_by='${escapeSqlString(input.rigHandle)}', ` +
    `stamp_id='${escapeSqlString(input.stamp.id)}', validated_at=NOW() ` +
    `WHERE id='${escapeSqlString(input.completionId)}'`;

  const updateWanted =
    `UPDATE wanted SET status='completed', updated_at=NOW() ` +
    `WHERE id='${escapeSqlString(input.wantedId)}' AND status='in_review'`;

  return [insertStamp, updateCompletion, updateWanted];
}

// AcceptUpstreamDML (commons.go:713)

export type AcceptUpstreamInput = {
  wantedId: string;
  completionId: string;
  completedBy: string;
  evidence: string;
  rigHandle: string;
  hopUri?: string;
  stamp: StampInput;
};

/**
 * Port of `AcceptUpstreamDML` (commons.go:713). Atomically adopts a fork's
 * completion onto the upstream branch: DELETE existing completion, INSERT
 * fork completion, UPDATE wanted, INSERT stamp, UPDATE completion w/ stamp ref.
 */
export function acceptUpstreamDML(input: AcceptUpstreamInput): string[] {
  const tagsField = formatTagsJson(input.stamp.skillTags);
  const msgField = sqlStringOrNull(input.stamp.message);
  const hopField = sqlStringOrNull(input.hopUri);

  const valence = `{"quality": ${input.stamp.quality}, "reliability": ${input.stamp.reliability}}`;

  const deleteCompletion = `DELETE FROM completions WHERE wanted_id='${escapeSqlString(input.wantedId)}'`;

  const insertCompletion =
    `INSERT IGNORE INTO completions (id, wanted_id, completed_by, evidence, hop_uri, completed_at) ` +
    `VALUES ('${escapeSqlString(input.completionId)}', '${escapeSqlString(input.wantedId)}', ` +
    `'${escapeSqlString(input.completedBy)}', '${escapeSqlString(input.evidence)}', ${hopField}, NOW())`;

  const updateWanted =
    `UPDATE wanted SET status='completed', claimed_by='${escapeSqlString(input.completedBy)}', ` +
    `evidence_url='${escapeSqlString(input.evidence)}', updated_at=NOW() ` +
    `WHERE id='${escapeSqlString(input.wantedId)}'`;

  const insertStamp =
    `INSERT INTO stamps (id, author, subject, valence, confidence, severity, context_id, context_type, skill_tags, message, hop_uri, created_at) ` +
    `VALUES ('${escapeSqlString(input.stamp.id)}', '${escapeSqlString(input.rigHandle)}', ` +
    `'${escapeSqlString(input.stamp.subject)}', '${escapeSqlString(valence)}', 1.0, ` +
    `'${escapeSqlString(input.stamp.severity)}', '${escapeSqlString(input.completionId)}', 'completion', ` +
    `${tagsField}, ${msgField}, ${hopField}, NOW())`;

  const updateCompletion =
    `UPDATE completions SET validated_by='${escapeSqlString(input.rigHandle)}', ` +
    `stamp_id='${escapeSqlString(input.stamp.id)}', validated_at=NOW() ` +
    `WHERE id='${escapeSqlString(input.completionId)}'`;

  return [deleteCompletion, insertCompletion, updateWanted, insertStamp, updateCompletion];
}

// CloseUpstreamDML (commons.go:751)

export type CloseUpstreamInput = {
  wantedId: string;
  completionId: string;
  completedBy: string;
  evidence: string;
  hopUri?: string;
};

/**
 * Port of `CloseUpstreamDML` (commons.go:751). Adopts a fork submission
 * without creating a stamp.
 */
export function closeUpstreamDML(input: CloseUpstreamInput): string[] {
  const hopField = sqlStringOrNull(input.hopUri);

  const deleteCompletion = `DELETE FROM completions WHERE wanted_id='${escapeSqlString(input.wantedId)}'`;

  const insertCompletion =
    `INSERT IGNORE INTO completions (id, wanted_id, completed_by, evidence, hop_uri, completed_at) ` +
    `VALUES ('${escapeSqlString(input.completionId)}', '${escapeSqlString(input.wantedId)}', ` +
    `'${escapeSqlString(input.completedBy)}', '${escapeSqlString(input.evidence)}', ${hopField}, NOW())`;

  const updateWanted =
    `UPDATE wanted SET status='completed', claimed_by='${escapeSqlString(input.completedBy)}', ` +
    `evidence_url='${escapeSqlString(input.evidence)}', updated_at=NOW() ` +
    `WHERE id='${escapeSqlString(input.wantedId)}'`;

  return [deleteCompletion, insertCompletion, updateWanted];
}

// UpdateWantedDML (commons.go:783)

export type WantedUpdateFields = {
  title?: string;
  description?: string;
  project?: string;
  type?: string;
  /** Use undefined or a negative number to leave priority unchanged. */
  priority?: number;
  effortLevel?: string;
  /** Set tags to a (possibly empty) array to update; leave undefined to skip. */
  tags?: readonly string[];
};

export type UpdateWantedInput = {
  wantedId: string;
  fields: WantedUpdateFields;
};

/**
 * Port of `UpdateWantedDML` (commons.go:783). Builds a partial UPDATE.
 * Throws if no fields are provided. The Go reference uses zero-values to mean
 * "not set"; we match that: empty strings, undefined, and negative priorities
 * are skipped. `tags` being present (even an empty array) marks it as set.
 */
export function updateWantedDML(input: UpdateWantedInput): string {
  const setClauses: string[] = [];
  const f = input.fields;

  if (f.title !== undefined && f.title !== '') {
    setClauses.push(`title='${escapeSqlString(f.title)}'`);
  }
  if (f.description !== undefined && f.description !== '') {
    setClauses.push(`description='${escapeSqlString(f.description)}'`);
  }
  if (f.project !== undefined && f.project !== '') {
    setClauses.push(`project='${escapeSqlString(f.project)}'`);
  }
  if (f.type !== undefined && f.type !== '') {
    setClauses.push(`type='${escapeSqlString(f.type)}'`);
  }
  if (f.priority !== undefined && f.priority >= 0) {
    setClauses.push(`priority=${f.priority}`);
  }
  if (f.effortLevel !== undefined && f.effortLevel !== '') {
    setClauses.push(`effort_level='${escapeSqlString(f.effortLevel)}'`);
  }
  if (f.tags !== undefined) {
    setClauses.push(`tags=${formatTagsJson(f.tags)}`);
  }

  if (setClauses.length === 0) {
    throw new Error('no fields to update');
  }

  setClauses.push('updated_at=NOW()');

  return `UPDATE wanted SET ${setClauses.join(', ')} WHERE id='${escapeSqlString(input.wantedId)}' AND status='open'`;
}

// CloseWantedDML (commons.go:836)

export type CloseWantedInput = {
  wantedId: string;
};

/** Port of `CloseWantedDML` (commons.go:836). */
export function closeWantedDML(input: CloseWantedInput): string {
  return (
    `UPDATE wanted SET status='completed', updated_at=NOW() ` +
    `WHERE id='${escapeSqlString(input.wantedId)}' AND status='in_review'`
  );
}

// DeleteWantedDML (commons.go:869)

export type DeleteWantedInput = {
  wantedId: string;
};

/** Port of `DeleteWantedDML` (commons.go:869). Soft-delete via status='withdrawn'. */
export function deleteWantedDML(input: DeleteWantedInput): string {
  return (
    `UPDATE wanted SET status='withdrawn', updated_at=NOW() ` +
    `WHERE id='${escapeSqlString(input.wantedId)}' AND status='open'`
  );
}

// RejectCompletionDML (commons.go:887)

export type RejectCompletionInput = {
  wantedId: string;
};

/** Port of `RejectCompletionDML` (commons.go:887). Returns DELETE + UPDATE. */
export function rejectCompletionDML(input: RejectCompletionInput): string[] {
  const wantedId = escapeSqlString(input.wantedId);
  return [
    `DELETE FROM completions WHERE wanted_id='${wantedId}'`,
    `UPDATE wanted SET status='claimed', updated_at=NOW() WHERE id='${wantedId}' AND status='in_review'`,
  ];
}
