// AUTO-GENERATED. Do not edit by hand.
// Source: wasteland/schema/commons.sql
// Generated by: packages/wl-sdk/scripts/generate-from-schema.ts
// To regenerate: pnpm --filter @kilocode/wl-sdk generate

import { z } from 'zod';

export const COMMONS_SCHEMA_VERSION = '1.2' as const;

export const MetaRowSchema = z.object({
  key: z.string(),
  value: z.string().nullable(),
});

export type MetaRow = z.infer<typeof MetaRowSchema>;

export const metaTable = {
  name: '_meta',
  columns: ['key', 'value'] as const,
  primaryKey: 'key',
} as const;

export const RigsRowSchema = z.object({
  handle: z.string(),
  display_name: z.string().nullable(),
  dolthub_org: z.string().nullable(),
  hop_uri: z.string().nullable(),
  owner_email: z.string().nullable(),
  gt_version: z.string().nullable(),
  trust_level: z.number().int().nullable(),
  registered_at: z.string().nullable(),
  last_seen: z.string().nullable(),
  rig_type: z.string().nullable(),
  parent_rig: z.string().nullable(),
});

export type RigsRow = z.infer<typeof RigsRowSchema>;

export const rigsTable = {
  name: 'rigs',
  columns: [
    'handle',
    'display_name',
    'dolthub_org',
    'hop_uri',
    'owner_email',
    'gt_version',
    'trust_level',
    'registered_at',
    'last_seen',
    'rig_type',
    'parent_rig',
  ] as const,
  primaryKey: 'handle',
} as const;

export const WantedRowSchema = z.object({
  id: z.string(),
  title: z.string(),
  description: z.string().nullable(),
  project: z.string().nullable(),
  type: z.string().nullable(),
  priority: z.coerce.number().int().nullable(),
  tags: z.unknown().nullable(),
  posted_by: z.string().nullable(),
  claimed_by: z.string().nullable(),
  status: z.string().nullable(),
  effort_level: z.string().nullable(),
  evidence_url: z.string().nullable(),
  sandbox_required: z.coerce.number().int().nullable(),
  sandbox_scope: z.unknown().nullable(),
  sandbox_min_tier: z.string().nullable(),
  created_at: z.string().nullable(),
  updated_at: z.string().nullable(),
});

export type WantedRow = z.infer<typeof WantedRowSchema>;

export const wantedTable = {
  name: 'wanted',
  columns: [
    'id',
    'title',
    'description',
    'project',
    'type',
    'priority',
    'tags',
    'posted_by',
    'claimed_by',
    'status',
    'effort_level',
    'evidence_url',
    'sandbox_required',
    'sandbox_scope',
    'sandbox_min_tier',
    'created_at',
    'updated_at',
  ] as const,
  primaryKey: 'id',
} as const;

export const CompletionsRowSchema = z.object({
  id: z.string(),
  wanted_id: z.string().nullable(),
  completed_by: z.string().nullable(),
  evidence: z.string().nullable(),
  validated_by: z.string().nullable(),
  stamp_id: z.string().nullable(),
  parent_completion_id: z.string().nullable(),
  block_hash: z.string().nullable(),
  hop_uri: z.string().nullable(),
  completed_at: z.string().nullable(),
  validated_at: z.string().nullable(),
});

export type CompletionsRow = z.infer<typeof CompletionsRowSchema>;

export const completionsTable = {
  name: 'completions',
  columns: [
    'id',
    'wanted_id',
    'completed_by',
    'evidence',
    'validated_by',
    'stamp_id',
    'parent_completion_id',
    'block_hash',
    'hop_uri',
    'completed_at',
    'validated_at',
  ] as const,
  primaryKey: 'id',
} as const;

export const StampsRowSchema = z.object({
  id: z.string(),
  author: z.string(),
  subject: z.string(),
  valence: z.unknown(),
  confidence: z.number().nullable(),
  severity: z.string().nullable(),
  context_id: z.string().nullable(),
  context_type: z.string().nullable(),
  skill_tags: z.unknown().nullable(),
  message: z.string().nullable(),
  prev_stamp_hash: z.string().nullable(),
  block_hash: z.string().nullable(),
  hop_uri: z.string().nullable(),
  created_at: z.string().nullable(),
});

export type StampsRow = z.infer<typeof StampsRowSchema>;

export const stampsTable = {
  name: 'stamps',
  columns: [
    'id',
    'author',
    'subject',
    'valence',
    'confidence',
    'severity',
    'context_id',
    'context_type',
    'skill_tags',
    'message',
    'prev_stamp_hash',
    'block_hash',
    'hop_uri',
    'created_at',
  ] as const,
  primaryKey: 'id',
} as const;

export const BadgesRowSchema = z.object({
  id: z.string(),
  rig_handle: z.string().nullable(),
  badge_type: z.string().nullable(),
  awarded_at: z.string().nullable(),
  evidence: z.string().nullable(),
});

export type BadgesRow = z.infer<typeof BadgesRowSchema>;

export const badgesTable = {
  name: 'badges',
  columns: ['id', 'rig_handle', 'badge_type', 'awarded_at', 'evidence'] as const,
  primaryKey: 'id',
} as const;

export const BootBlocksRowSchema = z.object({
  handle: z.string(),
  source: z.string(),
  sheet_json: z.unknown(),
  confidence: z.number(),
  version: z.string(),
  created_at: z.string(),
});

export type BootBlocksRow = z.infer<typeof BootBlocksRowSchema>;

export const bootBlocksTable = {
  name: 'boot_blocks',
  columns: ['handle', 'source', 'sheet_json', 'confidence', 'version', 'created_at'] as const,
  primaryKey: 'handle',
} as const;

export const ChainMetaRowSchema = z.object({
  chain_id: z.string(),
  chain_type: z.string().nullable(),
  parent_chain_id: z.string().nullable(),
  hop_uri: z.string().nullable(),
  dolt_database: z.string().nullable(),
  created_at: z.string().nullable(),
});

export type ChainMetaRow = z.infer<typeof ChainMetaRowSchema>;

export const chainMetaTable = {
  name: 'chain_meta',
  columns: [
    'chain_id',
    'chain_type',
    'parent_chain_id',
    'hop_uri',
    'dolt_database',
    'created_at',
  ] as const,
  primaryKey: 'chain_id',
} as const;

export const RigLinksRowSchema = z.object({
  id: z.string(),
  rig_a: z.string(),
  rig_b: z.string(),
  link_type: z.string().nullable(),
  assertion_a: z.string().nullable(),
  assertion_b: z.string().nullable(),
  status: z.string().nullable(),
  created_at: z.string().nullable(),
  completed_at: z.string().nullable(),
  revoked_at: z.string().nullable(),
  revoked_by: z.string().nullable(),
});

export type RigLinksRow = z.infer<typeof RigLinksRowSchema>;

export const rigLinksTable = {
  name: 'rig_links',
  columns: [
    'id',
    'rig_a',
    'rig_b',
    'link_type',
    'assertion_a',
    'assertion_b',
    'status',
    'created_at',
    'completed_at',
    'revoked_at',
    'revoked_by',
  ] as const,
  primaryKey: 'id',
} as const;

/**
 * The wasteland commons DDL split into individual statements, ready to
 * feed to DoltHub's write API one at a time. Order is preserved from
 * the source file. Statements have no trailing `;` so callers can append
 * one (or not) as the API expects.
 */
export const COMMONS_SCHEMA_STATEMENTS: readonly string[] = [
  `CREATE TABLE IF NOT EXISTS _meta (
    \`key\` VARCHAR(64) PRIMARY KEY,
    value TEXT
)`,

  `INSERT IGNORE INTO _meta (\`key\`, value) VALUES ('schema_version', '1.2')`,

  `CREATE TABLE IF NOT EXISTS rigs (
    handle VARCHAR(255) PRIMARY KEY,
    display_name VARCHAR(255),
    dolthub_org VARCHAR(255),
    hop_uri VARCHAR(512),
    owner_email VARCHAR(255),
    gt_version VARCHAR(32),
    trust_level INT DEFAULT 0,
    registered_at TIMESTAMP,
    last_seen TIMESTAMP,
    rig_type VARCHAR(16) DEFAULT 'human',
    parent_rig VARCHAR(255)
)`,

  `CREATE TABLE IF NOT EXISTS wanted (
    id VARCHAR(64) PRIMARY KEY,
    title TEXT NOT NULL,
    description TEXT,
    project VARCHAR(64),
    type VARCHAR(32),
    priority INT DEFAULT 2,
    tags JSON,
    posted_by VARCHAR(255),
    claimed_by VARCHAR(255),
    status VARCHAR(32) DEFAULT 'open',
    effort_level VARCHAR(16) DEFAULT 'medium',
    evidence_url TEXT,
    sandbox_required TINYINT(1) DEFAULT 0,
    sandbox_scope JSON,
    sandbox_min_tier VARCHAR(32),
    created_at TIMESTAMP,
    updated_at TIMESTAMP
)`,

  `CREATE TABLE IF NOT EXISTS completions (
    id VARCHAR(64) PRIMARY KEY,
    wanted_id VARCHAR(64),
    completed_by VARCHAR(255),
    evidence TEXT,
    validated_by VARCHAR(255),
    stamp_id VARCHAR(64),
    parent_completion_id VARCHAR(64),
    block_hash VARCHAR(64),
    hop_uri VARCHAR(512),
    completed_at TIMESTAMP,
    validated_at TIMESTAMP
)`,

  `CREATE TABLE IF NOT EXISTS stamps (
    id VARCHAR(64) PRIMARY KEY,
    author VARCHAR(255) NOT NULL,
    subject VARCHAR(255) NOT NULL,
    valence JSON NOT NULL,
    confidence FLOAT DEFAULT 1,
    severity VARCHAR(16) DEFAULT 'leaf',
    context_id VARCHAR(64),
    context_type VARCHAR(32),
    skill_tags JSON,
    message TEXT,
    prev_stamp_hash VARCHAR(64),
    block_hash VARCHAR(64),
    hop_uri VARCHAR(512),
    created_at TIMESTAMP,
    CHECK (NOT(author = subject))
)`,

  `CREATE TABLE IF NOT EXISTS badges (
    id VARCHAR(64) PRIMARY KEY,
    rig_handle VARCHAR(255),
    badge_type VARCHAR(64),
    awarded_at TIMESTAMP,
    evidence TEXT
)`,

  `CREATE TABLE IF NOT EXISTS boot_blocks (
    handle VARCHAR(255) NOT NULL PRIMARY KEY,
    source VARCHAR(64) NOT NULL,
    sheet_json JSON NOT NULL,
    confidence FLOAT NOT NULL,
    version VARCHAR(20) NOT NULL,
    created_at TIMESTAMP NOT NULL,
    CHECK (confidence BETWEEN 0.0 AND 1.0)
)`,

  `CREATE TABLE IF NOT EXISTS chain_meta (
    chain_id VARCHAR(64) PRIMARY KEY,
    chain_type VARCHAR(32),
    parent_chain_id VARCHAR(64),
    hop_uri VARCHAR(512),
    dolt_database VARCHAR(255),
    created_at TIMESTAMP
)`,

  `CREATE TABLE IF NOT EXISTS rig_links (
    id VARCHAR(64) PRIMARY KEY,
    rig_a VARCHAR(255) NOT NULL,
    rig_b VARCHAR(255) NOT NULL,
    link_type VARCHAR(32) DEFAULT 'same_owner',
    assertion_a TEXT,
    assertion_b TEXT,
    status VARCHAR(32) DEFAULT 'pending',
    created_at TIMESTAMP,
    completed_at TIMESTAMP,
    revoked_at TIMESTAMP,
    revoked_by VARCHAR(255),
    UNIQUE KEY uq_rig_pair (rig_a, rig_b),
    CHECK (rig_a != rig_b)
)`,
];
