/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: 2098c6191cf72df5e0020565df8425db)
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/wasteland.worker");
		durableNamespaces: "WastelandDO" | "WastelandRegistryDO";
	}
	interface DevEnv {
		WASTELAND_AE: AnalyticsEngineDataset;
		NEXTAUTH_SECRET: SecretsStoreSecret;
		WASTELAND_ENCRYPTION_KEY: SecretsStoreSecret;
		INTERNAL_API_SECRET: SecretsStoreSecret;
		ENVIRONMENT: "development";
		CF_ACCESS_TEAM: "engineering-e11";
		CF_ACCESS_AUD: "7f6eda4c0714f6ea2afb74a3f055db65659b67571a913eab42468636a9b8c8be";
		KILO_API_URL: "http://192.168.65.254:3000";
		KILO_INTERNAL_API_URL: "http://localhost:3000";
		WASTELAND_API_URL: "http://192.168.65.254:8787";
		WASTELAND: DurableObjectNamespace<import("./src/wasteland.worker").WastelandDO>;
		WASTELAND_REGISTRY: DurableObjectNamespace<import("./src/wasteland.worker").WastelandRegistryDO>;
	}
	interface Env {
		WASTELAND_AE: AnalyticsEngineDataset;
		NEXTAUTH_SECRET: SecretsStoreSecret;
		WASTELAND_ENCRYPTION_KEY: SecretsStoreSecret;
		INTERNAL_API_SECRET: SecretsStoreSecret;
		ENVIRONMENT: "development" | "production";
		CF_ACCESS_TEAM: "engineering-e11";
		CF_ACCESS_AUD: "7f6eda4c0714f6ea2afb74a3f055db65659b67571a913eab42468636a9b8c8be";
		KILO_API_URL: "http://192.168.65.254:3000" | "https://api.kilo.ai";
		KILO_INTERNAL_API_URL: "http://localhost:3000" | "https://api.kilo.ai";
		WASTELAND_API_URL: "http://192.168.65.254:8787" | "https://wasteland.kiloapps.io";
		WASTELAND: DurableObjectNamespace<import("./src/wasteland.worker").WastelandDO>;
		WASTELAND_REGISTRY: DurableObjectNamespace<import("./src/wasteland.worker").WastelandRegistryDO>;
		CF_VERSION_METADATA?: WorkerVersionMetadata;
		SENTRY_DSN?: string; // worker secret
		SENTRY_RELEASE?: string; // deploy-time --var
	}
}
interface Env extends Cloudflare.Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "ENVIRONMENT" | "CF_ACCESS_TEAM" | "CF_ACCESS_AUD" | "KILO_API_URL" | "KILO_INTERNAL_API_URL" | "WASTELAND_API_URL">> {}
}
