/**
 * `done` — submit completion evidence for a claimed wanted item.
 *
 * Mirrors `Client.Done` (`wasteland/internal/sdk/mutations.go:57`).
 *
 * `submitCompletionDML` returns two statements (UPDATE wanted +
 * INSERT completion). DoltHub's write API is one-statement-per-call,
 * so {@link applyMutation} fans them out across two writes onto the
 * same branch.
 */

import { submitCompletionDML } from '../commons/dml.generated';
import { applyMutation } from './mutate';
import type { DoneOutcome, MutationContext, WlResult } from './types';
import { WlError } from './types';

export type DoneOptions = {
  ctx: MutationContext;
  wantedId: string;
  /**
   * The completion evidence (URL to PR / commit / artifact). Required
   * by the Go reference; we mirror that here.
   */
  evidence: string;
  /** Optional hop URI that traces this completion across wastelands. */
  hopUri?: string;
  /**
   * The completion id. Generated by the caller; the wl-sdk does not
   * own ID generation. Per Go reference, ids look like
   * `c-<wantedId>-<rigHandle>-<short hash>`.
   */
  completionId: string;
};

export async function done(opts: DoneOptions): Promise<WlResult<DoneOutcome>> {
  try {
    const stmts = submitCompletionDML({
      completionId: opts.completionId,
      wantedId: opts.wantedId,
      rigHandle: opts.ctx.rigHandle,
      evidence: opts.evidence,
      hopUri: opts.hopUri,
    });
    const outcome = await applyMutation({
      ctx: opts.ctx,
      wantedId: opts.wantedId,
      targetStatus: 'in_review',
      statements: stmts,
      commitMessage: `wl done: ${opts.wantedId}`,
    });
    return { ok: true, data: { ...outcome, completionId: opts.completionId } };
  } catch (err) {
    if (err instanceof WlError) return { ok: false, error: err };
    return { ok: false, error: new WlError('done failed', 'internal', err) };
  }
}
