/**
 * Real session excerpt extracted from cloud-agent-ws-example.txt
 *
 * Source: First ~50 events of the first turn of a real Cloud Agent session.
 * The session involved a user asking to build a birthday invitation, with the
 * assistant spawning two child sessions (task subagents) to read project files.
 *
 * Events were filtered to remove non-interesting types (session.updated,
 * session.diff, session.turn.open/close, heartbeat, pong).
 *
 * Generated by: scripts/extract-fixture.ts
 */
import type { CloudAgentEvent } from '@/lib/cloud-agent-next/event-types';
import type { Fixture } from './types';

const events: CloudAgentEvent[] = [
  // --- Root session: user message ---
  // eventId 1: message.updated (user msg on root session)
  {
    eventId: 1,
    executionId: 'exc_01KJG3JPCCHN1SQV8AQXXGNJAA',
    sessionId: 'agent_e70285ed-91d1-4594-b2c7-8ae6ddae958c',
    streamEventType: 'kilocode',
    timestamp: '2026-02-27T17:50:40.152Z',
    data: {
      type: 'message.updated',
      properties: {
        info: {
          id: 'msg_ca0395def0011t6S1qwxQbPSYB',
          sessionID: 'ses_35fc6b339ffeaf91IozzdnLtJ7',
          role: 'user',
          time: { created: 1772214640111 },
          agent: 'code',
          model: { providerID: 'kilo', modelID: 'anthropic/claude-opus-4.6' },
        },
      },
      event: 'message.updated',
    },
  },
  // eventId 2: message.part.updated (user text part)
  {
    eventId: 2,
    executionId: 'exc_01KJG3JPCCHN1SQV8AQXXGNJAA',
    sessionId: 'agent_e70285ed-91d1-4594-b2c7-8ae6ddae958c',
    streamEventType: 'kilocode',
    timestamp: '2026-02-27T17:50:40.152Z',
    data: {
      type: 'message.part.updated',
      properties: {
        part: {
          id: 'prt_ca0395df1001ez5Rq0YoFEEjdO',
          sessionID: 'ses_35fc6b339ffeaf91IozzdnLtJ7',
          messageID: 'msg_ca0395def0011t6S1qwxQbPSYB',
          type: 'text',
          text: "I want to build mobile portrait mode friendly interactive birthday invitation for an upcoming 6 year old girl party. Please suggest some cool ideas and let's implement.",
        },
      },
      event: 'message.part.updated',
    },
  },

  // --- Root session: busy + assistant message ---
  // eventId 5: session.status busy
  {
    eventId: 5,
    executionId: 'exc_01KJG3JPCCHN1SQV8AQXXGNJAA',
    sessionId: 'agent_e70285ed-91d1-4594-b2c7-8ae6ddae958c',
    streamEventType: 'kilocode',
    timestamp: '2026-02-27T17:50:40.152Z',
    data: {
      type: 'session.status',
      properties: { sessionID: 'ses_35fc6b339ffeaf91IozzdnLtJ7', status: { type: 'busy' } },
      event: 'session.status',
    },
  },
  // eventId 6: message.updated (assistant msg)
  {
    eventId: 6,
    executionId: 'exc_01KJG3JPCCHN1SQV8AQXXGNJAA',
    sessionId: 'agent_e70285ed-91d1-4594-b2c7-8ae6ddae958c',
    streamEventType: 'kilocode',
    timestamp: '2026-02-27T17:50:40.432Z',
    data: {
      type: 'message.updated',
      properties: {
        info: {
          id: 'msg_ca0395ef9001ujtPhZR1a8WqB3',
          sessionID: 'ses_35fc6b339ffeaf91IozzdnLtJ7',
          role: 'assistant',
          time: { created: 1772214640377 },
          parentID: 'msg_ca0395def0011t6S1qwxQbPSYB',
          modelID: 'anthropic/claude-opus-4.6',
          providerID: 'kilo',
          mode: 'code',
          agent: 'code',
          path: { cwd: '/workspace', root: '/workspace' },
          cost: 0,
          tokens: { input: 0, output: 0, reasoning: 0, cache: { read: 0, write: 0 } },
        },
      },
      event: 'message.updated',
    },
  },

  // --- Assistant streaming: step-start + text deltas ---
  // eventId 11: step-start
  {
    eventId: 11,
    executionId: 'exc_01KJG3JPCCHN1SQV8AQXXGNJAA',
    sessionId: 'agent_e70285ed-91d1-4594-b2c7-8ae6ddae958c',
    streamEventType: 'kilocode',
    timestamp: '2026-02-27T17:50:43.076Z',
    data: {
      type: 'message.part.updated',
      properties: {
        part: {
          id: 'prt_ca0396973001W5HQXfBJO1noCZ',
          sessionID: 'ses_35fc6b339ffeaf91IozzdnLtJ7',
          messageID: 'msg_ca0395ef9001ujtPhZR1a8WqB3',
          type: 'step-start',
          snapshot: '87ed3a88ba5568e1386f8cc59ddbdb76d45063fd',
        },
      },
      event: 'message.part.updated',
    },
  },
  // eventId 12: empty text part (before deltas)
  {
    eventId: 12,
    executionId: 'exc_01KJG3JPCCHN1SQV8AQXXGNJAA',
    sessionId: 'agent_e70285ed-91d1-4594-b2c7-8ae6ddae958c',
    streamEventType: 'kilocode',
    timestamp: '2026-02-27T17:50:43.076Z',
    data: {
      type: 'message.part.updated',
      properties: {
        part: {
          id: 'prt_ca0396978001gMbv1ux5m6rlAq',
          sessionID: 'ses_35fc6b339ffeaf91IozzdnLtJ7',
          messageID: 'msg_ca0395ef9001ujtPhZR1a8WqB3',
          type: 'text',
          text: '',
          time: { start: 1772214643064 },
        },
      },
      event: 'message.part.updated',
    },
  },
  // eventId 13-21: text deltas
  {
    eventId: 13,
    executionId: 'exc_01KJG3JPCCHN1SQV8AQXXGNJAA',
    sessionId: 'agent_e70285ed-91d1-4594-b2c7-8ae6ddae958c',
    streamEventType: 'kilocode',
    timestamp: '2026-02-27T17:50:43.076Z',
    data: {
      type: 'message.part.delta',
      properties: {
        sessionID: 'ses_35fc6b339ffeaf91IozzdnLtJ7',
        messageID: 'msg_ca0395ef9001ujtPhZR1a8WqB3',
        partID: 'prt_ca0396978001gMbv1ux5m6rlAq',
        field: 'text',
        delta: "\n\nI'll",
      },
      event: 'message.part.delta',
    },
  },
  {
    eventId: 14,
    executionId: 'exc_01KJG3JPCCHN1SQV8AQXXGNJAA',
    sessionId: 'agent_e70285ed-91d1-4594-b2c7-8ae6ddae958c',
    streamEventType: 'kilocode',
    timestamp: '2026-02-27T17:50:43.076Z',
    data: {
      type: 'message.part.delta',
      properties: {
        sessionID: 'ses_35fc6b339ffeaf91IozzdnLtJ7',
        messageID: 'msg_ca0395ef9001ujtPhZR1a8WqB3',
        partID: 'prt_ca0396978001gMbv1ux5m6rlAq',
        field: 'text',
        delta: ' start',
      },
      event: 'message.part.delta',
    },
  },
  {
    eventId: 15,
    executionId: 'exc_01KJG3JPCCHN1SQV8AQXXGNJAA',
    sessionId: 'agent_e70285ed-91d1-4594-b2c7-8ae6ddae958c',
    streamEventType: 'kilocode',
    timestamp: '2026-02-27T17:50:43.080Z',
    data: {
      type: 'message.part.delta',
      properties: {
        sessionID: 'ses_35fc6b339ffeaf91IozzdnLtJ7',
        messageID: 'msg_ca0395ef9001ujtPhZR1a8WqB3',
        partID: 'prt_ca0396978001gMbv1ux5m6rlAq',
        field: 'text',
        delta: ' by reading',
      },
      event: 'message.part.delta',
    },
  },
  {
    eventId: 16,
    executionId: 'exc_01KJG3JPCCHN1SQV8AQXXGNJAA',
    sessionId: 'agent_e70285ed-91d1-4594-b2c7-8ae6ddae958c',
    streamEventType: 'kilocode',
    timestamp: '2026-02-27T17:50:43.122Z',
    data: {
      type: 'message.part.delta',
      properties: {
        sessionID: 'ses_35fc6b339ffeaf91IozzdnLtJ7',
        messageID: 'msg_ca0395ef9001ujtPhZR1a8WqB3',
        partID: 'prt_ca0396978001gMbv1ux5m6rlAq',
        field: 'text',
        delta: ' the memory bank files',
      },
      event: 'message.part.delta',
    },
  },
  {
    eventId: 17,
    executionId: 'exc_01KJG3JPCCHN1SQV8AQXXGNJAA',
    sessionId: 'agent_e70285ed-91d1-4594-b2c7-8ae6ddae958c',
    streamEventType: 'kilocode',
    timestamp: '2026-02-27T17:50:43.167Z',
    data: {
      type: 'message.part.delta',
      properties: {
        sessionID: 'ses_35fc6b339ffeaf91IozzdnLtJ7',
        messageID: 'msg_ca0395ef9001ujtPhZR1a8WqB3',
        partID: 'prt_ca0396978001gMbv1ux5m6rlAq',
        field: 'text',
        delta: ' to understand the project',
      },
      event: 'message.part.delta',
    },
  },
  {
    eventId: 18,
    executionId: 'exc_01KJG3JPCCHN1SQV8AQXXGNJAA',
    sessionId: 'agent_e70285ed-91d1-4594-b2c7-8ae6ddae958c',
    streamEventType: 'kilocode',
    timestamp: '2026-02-27T17:50:43.220Z',
    data: {
      type: 'message.part.delta',
      properties: {
        sessionID: 'ses_35fc6b339ffeaf91IozzdnLtJ7',
        messageID: 'msg_ca0395ef9001ujtPhZR1a8WqB3',
        partID: 'prt_ca0396978001gMbv1ux5m6rlAq',
        field: 'text',
        delta: ' context',
      },
      event: 'message.part.delta',
    },
  },
  {
    eventId: 19,
    executionId: 'exc_01KJG3JPCCHN1SQV8AQXXGNJAA',
    sessionId: 'agent_e70285ed-91d1-4594-b2c7-8ae6ddae958c',
    streamEventType: 'kilocode',
    timestamp: '2026-02-27T17:50:43.277Z',
    data: {
      type: 'message.part.delta',
      properties: {
        sessionID: 'ses_35fc6b339ffeaf91IozzdnLtJ7',
        messageID: 'msg_ca0395ef9001ujtPhZR1a8WqB3',
        partID: 'prt_ca0396978001gMbv1ux5m6rlAq',
        field: 'text',
        delta: ', then suggest some creative ideas',
      },
      event: 'message.part.delta',
    },
  },
  {
    eventId: 20,
    executionId: 'exc_01KJG3JPCCHN1SQV8AQXXGNJAA',
    sessionId: 'agent_e70285ed-91d1-4594-b2c7-8ae6ddae958c',
    streamEventType: 'kilocode',
    timestamp: '2026-02-27T17:50:43.324Z',
    data: {
      type: 'message.part.delta',
      properties: {
        sessionID: 'ses_35fc6b339ffeaf91IozzdnLtJ7',
        messageID: 'msg_ca0395ef9001ujtPhZR1a8WqB3',
        partID: 'prt_ca0396978001gMbv1ux5m6rlAq',
        field: 'text',
        delta: ' for the',
      },
      event: 'message.part.delta',
    },
  },
  {
    eventId: 21,
    executionId: 'exc_01KJG3JPCCHN1SQV8AQXXGNJAA',
    sessionId: 'agent_e70285ed-91d1-4594-b2c7-8ae6ddae958c',
    streamEventType: 'kilocode',
    timestamp: '2026-02-27T17:50:43.374Z',
    data: {
      type: 'message.part.delta',
      properties: {
        sessionID: 'ses_35fc6b339ffeaf91IozzdnLtJ7',
        messageID: 'msg_ca0395ef9001ujtPhZR1a8WqB3',
        partID: 'prt_ca0396978001gMbv1ux5m6rlAq',
        field: 'text',
        delta: ' birthday invitation.',
      },
      event: 'message.part.delta',
    },
  },

  // --- First tool part (task: "Read memory bank files") ---
  // eventId 22: tool pending
  {
    eventId: 22,
    executionId: 'exc_01KJG3JPCCHN1SQV8AQXXGNJAA',
    sessionId: 'agent_e70285ed-91d1-4594-b2c7-8ae6ddae958c',
    streamEventType: 'kilocode',
    timestamp: '2026-02-27T17:50:43.591Z',
    data: {
      type: 'message.part.updated',
      properties: {
        part: {
          id: 'prt_ca0396b84001XskRRHNNDW332o',
          sessionID: 'ses_35fc6b339ffeaf91IozzdnLtJ7',
          messageID: 'msg_ca0395ef9001ujtPhZR1a8WqB3',
          type: 'tool',
          callID: 'toolu_bdrk_01U4m8xFK9kfXq9hjFXgK6jh',
          tool: 'task',
          state: { status: 'pending', input: {}, raw: '' },
        },
      },
      event: 'message.part.updated',
    },
  },
  // eventId 23: tool running
  {
    eventId: 23,
    executionId: 'exc_01KJG3JPCCHN1SQV8AQXXGNJAA',
    sessionId: 'agent_e70285ed-91d1-4594-b2c7-8ae6ddae958c',
    streamEventType: 'kilocode',
    timestamp: '2026-02-27T17:50:45.485Z',
    data: {
      type: 'message.part.updated',
      properties: {
        part: {
          id: 'prt_ca0396b84001XskRRHNNDW332o',
          sessionID: 'ses_35fc6b339ffeaf91IozzdnLtJ7',
          messageID: 'msg_ca0395ef9001ujtPhZR1a8WqB3',
          type: 'tool',
          callID: 'toolu_bdrk_01U4m8xFK9kfXq9hjFXgK6jh',
          tool: 'task',
          state: {
            status: 'running',
            input: {
              description: 'Read memory bank files',
              prompt: 'Read ALL files in the .kilocode/rules/memory-bank/ directory...',
              subagent_type: 'explore',
            },
            time: { start: 1772214645446 },
          },
          metadata: { openrouter: { reasoning_details: [] } },
        },
      },
      event: 'message.part.updated',
    },
  },

  // --- Child session 1: crisp-falcon (Read memory bank files) ---
  // eventId 24: session.created
  {
    eventId: 24,
    executionId: 'exc_01KJG3JPCCHN1SQV8AQXXGNJAA',
    sessionId: 'agent_e70285ed-91d1-4594-b2c7-8ae6ddae958c',
    streamEventType: 'kilocode',
    timestamp: '2026-02-27T17:50:45.486Z',
    data: {
      type: 'session.created',
      properties: {
        info: {
          id: 'ses_35fc68d34ffekdeV5TnynoACK6',
          slug: 'crisp-falcon',
          version: '7.0.29',
          projectID: '859bac4e95c8a8508b6ec3e4faa3c473f5c6b451',
          directory: '/workspace',
          parentID: 'ses_35fc6b339ffeaf91IozzdnLtJ7',
          title: 'Read memory bank files (@explore subagent)',
          permission: [
            { permission: 'todowrite', pattern: '*', action: 'deny' },
            { permission: 'todoread', pattern: '*', action: 'deny' },
            { permission: 'task', pattern: '*', action: 'deny' },
          ],
          time: { created: 1772214645451, updated: 1772214645451 },
        },
      },
      event: 'session.created',
    },
  },
  // eventId 26: tool part updated with child session metadata
  {
    eventId: 26,
    executionId: 'exc_01KJG3JPCCHN1SQV8AQXXGNJAA',
    sessionId: 'agent_e70285ed-91d1-4594-b2c7-8ae6ddae958c',
    streamEventType: 'kilocode',
    timestamp: '2026-02-27T17:50:45.486Z',
    data: {
      type: 'message.part.updated',
      properties: {
        part: {
          id: 'prt_ca0396b84001XskRRHNNDW332o',
          sessionID: 'ses_35fc6b339ffeaf91IozzdnLtJ7',
          messageID: 'msg_ca0395ef9001ujtPhZR1a8WqB3',
          type: 'tool',
          callID: 'toolu_bdrk_01U4m8xFK9kfXq9hjFXgK6jh',
          tool: 'task',
          state: {
            status: 'running',
            input: {
              description: 'Read memory bank files',
              prompt: 'Read ALL files in the .kilocode/rules/memory-bank/ directory...',
              subagent_type: 'explore',
            },
            title: 'Read memory bank files',
            metadata: {
              sessionId: 'ses_35fc68d34ffekdeV5TnynoACK6',
              model: { modelID: 'anthropic/claude-opus-4.6', providerID: 'kilo' },
            },
            time: { start: 1772214645457 },
          },
          metadata: { openrouter: { reasoning_details: [] } },
        },
      },
      event: 'message.part.updated',
    },
  },
  // eventId 27: child 1 user message
  {
    eventId: 27,
    executionId: 'exc_01KJG3JPCCHN1SQV8AQXXGNJAA',
    sessionId: 'agent_e70285ed-91d1-4594-b2c7-8ae6ddae958c',
    streamEventType: 'kilocode',
    timestamp: '2026-02-27T17:50:45.487Z',
    data: {
      type: 'message.updated',
      properties: {
        info: {
          id: 'msg_ca03972d2001YoiiEdyqkQzppR',
          sessionID: 'ses_35fc68d34ffekdeV5TnynoACK6',
          role: 'user',
          time: { created: 1772214645461 },
          agent: 'explore',
          model: { providerID: 'kilo', modelID: 'anthropic/claude-opus-4.6' },
          tools: { todowrite: false, todoread: false, task: false },
        },
      },
      event: 'message.updated',
    },
  },
  // eventId 28: child 1 user text part
  {
    eventId: 28,
    executionId: 'exc_01KJG3JPCCHN1SQV8AQXXGNJAA',
    sessionId: 'agent_e70285ed-91d1-4594-b2c7-8ae6ddae958c',
    streamEventType: 'kilocode',
    timestamp: '2026-02-27T17:50:45.487Z',
    data: {
      type: 'message.part.updated',
      properties: {
        part: {
          id: 'prt_ca03972d50011ux1RH7b0z6RxJ',
          sessionID: 'ses_35fc68d34ffekdeV5TnynoACK6',
          messageID: 'msg_ca03972d2001YoiiEdyqkQzppR',
          type: 'text',
          text: 'Read ALL files in the .kilocode/rules/memory-bank/ directory and return their full contents. Also read .kilocode/rules/development.md and any recipe files in .kilocode/recipes/. Return the complete content of each file.',
        },
      },
      event: 'message.part.updated',
    },
  },
  // eventId 32: child 1 session busy
  {
    eventId: 32,
    executionId: 'exc_01KJG3JPCCHN1SQV8AQXXGNJAA',
    sessionId: 'agent_e70285ed-91d1-4594-b2c7-8ae6ddae958c',
    streamEventType: 'kilocode',
    timestamp: '2026-02-27T17:50:45.488Z',
    data: {
      type: 'session.status',
      properties: { sessionID: 'ses_35fc68d34ffekdeV5TnynoACK6', status: { type: 'busy' } },
      event: 'session.status',
    },
  },
  // eventId 33: child 1 assistant message
  {
    eventId: 33,
    executionId: 'exc_01KJG3JPCCHN1SQV8AQXXGNJAA',
    sessionId: 'agent_e70285ed-91d1-4594-b2c7-8ae6ddae958c',
    streamEventType: 'kilocode',
    timestamp: '2026-02-27T17:50:45.488Z',
    data: {
      type: 'message.updated',
      properties: {
        info: {
          id: 'msg_ca03972de001LcndWje47uLasC',
          sessionID: 'ses_35fc68d34ffekdeV5TnynoACK6',
          role: 'assistant',
          time: { created: 1772214645470 },
          parentID: 'msg_ca03972d2001YoiiEdyqkQzppR',
          modelID: 'anthropic/claude-opus-4.6',
          providerID: 'kilo',
          mode: 'explore',
          agent: 'explore',
          path: { cwd: '/workspace', root: '/workspace' },
          cost: 0,
          tokens: { input: 0, output: 0, reasoning: 0, cache: { read: 0, write: 0 } },
        },
      },
      event: 'message.updated',
    },
  },

  // --- Second tool part (task: "Explore project structure") ---
  // eventId 34: second tool pending
  {
    eventId: 34,
    executionId: 'exc_01KJG3JPCCHN1SQV8AQXXGNJAA',
    sessionId: 'agent_e70285ed-91d1-4594-b2c7-8ae6ddae958c',
    streamEventType: 'kilocode',
    timestamp: '2026-02-27T17:50:45.488Z',
    data: {
      type: 'message.part.updated',
      properties: {
        part: {
          id: 'prt_ca03972ea001js7nTR18yPN9eE',
          sessionID: 'ses_35fc6b339ffeaf91IozzdnLtJ7',
          messageID: 'msg_ca0395ef9001ujtPhZR1a8WqB3',
          type: 'tool',
          callID: 'toolu_bdrk_01E4v8PzobEawWnTC26AeRND',
          tool: 'task',
          state: { status: 'pending', input: {}, raw: '' },
        },
      },
      event: 'message.part.updated',
    },
  },
  // eventId 39: second tool running
  {
    eventId: 39,
    executionId: 'exc_01KJG3JPCCHN1SQV8AQXXGNJAA',
    sessionId: 'agent_e70285ed-91d1-4594-b2c7-8ae6ddae958c',
    streamEventType: 'kilocode',
    timestamp: '2026-02-27T17:50:47.952Z',
    data: {
      type: 'message.part.updated',
      properties: {
        part: {
          id: 'prt_ca03972ea001js7nTR18yPN9eE',
          sessionID: 'ses_35fc6b339ffeaf91IozzdnLtJ7',
          messageID: 'msg_ca0395ef9001ujtPhZR1a8WqB3',
          type: 'tool',
          callID: 'toolu_bdrk_01E4v8PzobEawWnTC26AeRND',
          tool: 'task',
          state: {
            status: 'running',
            input: {
              description: 'Explore project structure',
              prompt: 'Explore the project structure...',
              subagent_type: 'explore',
            },
            time: { start: 1772214647910 },
          },
          metadata: { openrouter: { reasoning_details: [] } },
        },
      },
      event: 'message.part.updated',
    },
  },

  // --- Child session 2: nimble-falcon (Explore project structure) ---
  // eventId 40: session.created
  {
    eventId: 40,
    executionId: 'exc_01KJG3JPCCHN1SQV8AQXXGNJAA',
    sessionId: 'agent_e70285ed-91d1-4594-b2c7-8ae6ddae958c',
    streamEventType: 'kilocode',
    timestamp: '2026-02-27T17:50:47.952Z',
    data: {
      type: 'session.created',
      properties: {
        info: {
          id: 'ses_35fc68395ffeX5M3nKm87BY4DK',
          slug: 'nimble-falcon',
          version: '7.0.29',
          projectID: '859bac4e95c8a8508b6ec3e4faa3c473f5c6b451',
          directory: '/workspace',
          parentID: 'ses_35fc6b339ffeaf91IozzdnLtJ7',
          title: 'Explore project structure (@explore subagent)',
          permission: [
            { permission: 'todowrite', pattern: '*', action: 'deny' },
            { permission: 'todoread', pattern: '*', action: 'deny' },
            { permission: 'task', pattern: '*', action: 'deny' },
          ],
          time: { created: 1772214647914, updated: 1772214647914 },
        },
      },
      event: 'session.created',
    },
  },
  // eventId 42: second tool part updated with child session metadata
  {
    eventId: 42,
    executionId: 'exc_01KJG3JPCCHN1SQV8AQXXGNJAA',
    sessionId: 'agent_e70285ed-91d1-4594-b2c7-8ae6ddae958c',
    streamEventType: 'kilocode',
    timestamp: '2026-02-27T17:50:47.952Z',
    data: {
      type: 'message.part.updated',
      properties: {
        part: {
          id: 'prt_ca03972ea001js7nTR18yPN9eE',
          sessionID: 'ses_35fc6b339ffeaf91IozzdnLtJ7',
          messageID: 'msg_ca0395ef9001ujtPhZR1a8WqB3',
          type: 'tool',
          callID: 'toolu_bdrk_01E4v8PzobEawWnTC26AeRND',
          tool: 'task',
          state: {
            status: 'running',
            input: {
              description: 'Explore project structure',
              prompt: 'Explore the project structure...',
              subagent_type: 'explore',
            },
            title: 'Explore project structure',
            metadata: {
              sessionId: 'ses_35fc68395ffeX5M3nKm87BY4DK',
              model: { modelID: 'anthropic/claude-opus-4.6', providerID: 'kilo' },
            },
            time: { start: 1772214647917 },
          },
          metadata: { openrouter: { reasoning_details: [] } },
        },
      },
      event: 'message.part.updated',
    },
  },
  // eventId 43: child 2 user message
  {
    eventId: 43,
    executionId: 'exc_01KJG3JPCCHN1SQV8AQXXGNJAA',
    sessionId: 'agent_e70285ed-91d1-4594-b2c7-8ae6ddae958c',
    streamEventType: 'kilocode',
    timestamp: '2026-02-27T17:50:47.952Z',
    data: {
      type: 'message.updated',
      properties: {
        info: {
          id: 'msg_ca0397c6e001qkgAbbJuoTl1v8',
          sessionID: 'ses_35fc68395ffeX5M3nKm87BY4DK',
          role: 'user',
          time: { created: 1772214647920 },
          agent: 'explore',
          model: { providerID: 'kilo', modelID: 'anthropic/claude-opus-4.6' },
          tools: { todowrite: false, todoread: false, task: false },
        },
      },
      event: 'message.updated',
    },
  },
  // eventId 44: child 2 user text part
  {
    eventId: 44,
    executionId: 'exc_01KJG3JPCCHN1SQV8AQXXGNJAA',
    sessionId: 'agent_e70285ed-91d1-4594-b2c7-8ae6ddae958c',
    streamEventType: 'kilocode',
    timestamp: '2026-02-27T17:50:47.952Z',
    data: {
      type: 'message.part.updated',
      properties: {
        part: {
          id: 'prt_ca0397c70001i5sib3HEV6UzQX',
          sessionID: 'ses_35fc68395ffeX5M3nKm87BY4DK',
          messageID: 'msg_ca0397c6e001qkgAbbJuoTl1v8',
          type: 'text',
          text: 'Explore the project structure thoroughly. I need to understand:\n1. What framework is being used (Next.js, etc.)\n2. What the current app structure looks like (pages, components, styles)\n3. What dependencies are installed (check package.json)\n4. What the current homepage looks like (read the main page file)\n5. Any existing components or layouts\n6. The tailwind config if present\n7. The next.config file if present\n\nReturn all file contents and a summary of the project structure.',
        },
      },
      event: 'message.part.updated',
    },
  },
  // eventId 48: child 2 session busy
  {
    eventId: 48,
    executionId: 'exc_01KJG3JPCCHN1SQV8AQXXGNJAA',
    sessionId: 'agent_e70285ed-91d1-4594-b2c7-8ae6ddae958c',
    streamEventType: 'kilocode',
    timestamp: '2026-02-27T17:50:47.952Z',
    data: {
      type: 'session.status',
      properties: { sessionID: 'ses_35fc68395ffeX5M3nKm87BY4DK', status: { type: 'busy' } },
      event: 'session.status',
    },
  },
  // eventId 49: child 2 assistant message
  {
    eventId: 49,
    executionId: 'exc_01KJG3JPCCHN1SQV8AQXXGNJAA',
    sessionId: 'agent_e70285ed-91d1-4594-b2c7-8ae6ddae958c',
    streamEventType: 'kilocode',
    timestamp: '2026-02-27T17:50:47.953Z',
    data: {
      type: 'message.updated',
      properties: {
        info: {
          id: 'msg_ca0397c79001rlvO57IC7yCGSw',
          sessionID: 'ses_35fc68395ffeX5M3nKm87BY4DK',
          role: 'assistant',
          time: { created: 1772214647929 },
          parentID: 'msg_ca0397c6e001qkgAbbJuoTl1v8',
          modelID: 'anthropic/claude-opus-4.6',
          providerID: 'kilo',
          mode: 'explore',
          agent: 'explore',
          path: { cwd: '/workspace', root: '/workspace' },
          cost: 0,
          tokens: { input: 0, output: 0, reasoning: 0, cache: { read: 0, write: 0 } },
        },
      },
      event: 'message.updated',
    },
  },

  // --- Root assistant text snapshot (replaces deltas) ---
  // eventId 50: final text snapshot for root assistant text part
  {
    eventId: 50,
    executionId: 'exc_01KJG3JPCCHN1SQV8AQXXGNJAA',
    sessionId: 'agent_e70285ed-91d1-4594-b2c7-8ae6ddae958c',
    streamEventType: 'kilocode',
    timestamp: '2026-02-27T17:50:47.953Z',
    data: {
      type: 'message.part.updated',
      properties: {
        part: {
          id: 'prt_ca0396978001gMbv1ux5m6rlAq',
          sessionID: 'ses_35fc6b339ffeaf91IozzdnLtJ7',
          messageID: 'msg_ca0395ef9001ujtPhZR1a8WqB3',
          type: 'text',
          text: "\n\nI'll start by reading the memory bank files to understand the project context, then suggest some creative ideas for the birthday invitation.",
          time: { start: 1772214647942, end: 1772214647942 },
        },
      },
      event: 'message.part.updated',
    },
  },

  // --- Turn complete ---
  // eventId 1971: complete (from end of first turn, line 1973)
  {
    eventId: 1971,
    executionId: 'exc_01KJG3JPCCHN1SQV8AQXXGNJAA',
    sessionId: 'agent_e70285ed-91d1-4594-b2c7-8ae6ddae958c',
    streamEventType: 'complete',
    timestamp: '2026-02-27T17:57:56.504Z',
    data: {
      exitCode: 0,
      executionId: 'exc_01KJG3JPCCHN1SQV8AQXXGNJAA',
      kiloSessionId: 'ses_35fc6b339ffeaf91IozzdnLtJ7',
    },
  },
];

/**
 * Expected state after replaying all events through the normalizer.
 *
 * Messages (sorted by ID):
 *   - msg_ca0395def0011t6S1qwxQbPSYB  (root user)
 *   - msg_ca0395ef9001ujtPhZR1a8WqB3  (root assistant)
 *   - msg_ca03972d2001YoiiEdyqkQzppR  (child 1 user)
 *   - msg_ca03972de001LcndWje47uLasC  (child 1 assistant)
 *   - msg_ca0397c6e001qkgAbbJuoTl1v8  (child 2 user)
 *   - msg_ca0397c79001rlvO57IC7yCGSw  (child 2 assistant)
 *
 * Parts: last message.part.updated snapshot wins for each partId.
 *   The text deltas (eventId 13-21) are superseded by the final snapshot (eventId 50).
 *   Tool parts: last snapshot for each tool partId determines final state.
 */
const realSessionExcerpt: Fixture = {
  name: 'real-session-excerpt',
  description:
    'Real WebSocket excerpt: root session with user/assistant messages, text streaming via deltas, ' +
    'two task tool parts spawning child sessions, each with user/assistant messages. ' +
    'Extracted from cloud-agent-ws-example.txt first turn.',
  events,
  expected: {
    messageIds: [
      'msg_ca0395def0011t6S1qwxQbPSYB',
      'msg_ca0395ef9001ujtPhZR1a8WqB3',
      'msg_ca03972d2001YoiiEdyqkQzppR',
      'msg_ca03972de001LcndWje47uLasC',
      'msg_ca0397c6e001qkgAbbJuoTl1v8',
      'msg_ca0397c79001rlvO57IC7yCGSw',
    ],
    parts: {
      // Root user message: single text part
      msg_ca0395def0011t6S1qwxQbPSYB: [
        {
          id: 'prt_ca0395df1001ez5Rq0YoFEEjdO',
          type: 'text',
          text: "I want to build mobile portrait mode friendly interactive birthday invitation for an upcoming 6 year old girl party. Please suggest some cool ideas and let's implement.",
        },
      ],
      // Root assistant message: step-start + text (snapshot wins over deltas) + 2 tool parts
      msg_ca0395ef9001ujtPhZR1a8WqB3: [
        {
          id: 'prt_ca0396973001W5HQXfBJO1noCZ',
          type: 'step-start',
        },
        {
          id: 'prt_ca0396978001gMbv1ux5m6rlAq',
          type: 'text',
          text: "\n\nI'll start by reading the memory bank files to understand the project context, then suggest some creative ideas for the birthday invitation.",
        },
        {
          id: 'prt_ca0396b84001XskRRHNNDW332o',
          type: 'tool',
          tool: 'task',
        },
        {
          id: 'prt_ca03972ea001js7nTR18yPN9eE',
          type: 'tool',
          tool: 'task',
        },
      ],
      // Child 1 user message: single text part
      msg_ca03972d2001YoiiEdyqkQzppR: [
        {
          id: 'prt_ca03972d50011ux1RH7b0z6RxJ',
          type: 'text',
          text: 'Read ALL files in the .kilocode/rules/memory-bank/ directory and return their full contents. Also read .kilocode/rules/development.md and any recipe files in .kilocode/recipes/. Return the complete content of each file.',
        },
      ],
      // Child 1 assistant message: no parts in this excerpt (assistant msg created but no parts yet)
      msg_ca03972de001LcndWje47uLasC: [],
      // Child 2 user message: single text part
      msg_ca0397c6e001qkgAbbJuoTl1v8: [
        {
          id: 'prt_ca0397c70001i5sib3HEV6UzQX',
          type: 'text',
          text: 'Explore the project structure thoroughly. I need to understand:\n1. What framework is being used (Next.js, etc.)\n2. What the current app structure looks like (pages, components, styles)\n3. What dependencies are installed (check package.json)\n4. What the current homepage looks like (read the main page file)\n5. Any existing components or layouts\n6. The tailwind config if present\n7. The next.config file if present\n\nReturn all file contents and a summary of the project structure.',
        },
      ],
      // Child 2 assistant message: no parts in this excerpt
      msg_ca0397c79001rlvO57IC7yCGSw: [],
    },
  },
};

export { realSessionExcerpt };
