import type React from 'react';

export type EditorVisibility = 'show' | 'hide' | 'show-when-expanded';

export interface EditorOption {
  source: string;
  name: string;
  label: string;
  scheme: string;
  host: string;
  path: string;
  extensionUrl: string;
  downloadUrl?: string;
  logoSrc: string;
  alt: string;
  logoStyle?: React.CSSProperties;
  visibilityOnInstallPage: EditorVisibility;
}

const VSCODE_EXTENSION_HOST = `kilocode.kilo-code`;
const VSCODE_EXTENSION_PATH = `/kilocode`;
const JETBRAINS_EXTENSION_PATH = `/ai.kilocode.jetbrains.auth`;

export const EDITOR_OPTIONS: EditorOption[] = [
  {
    source: 'vscode',
    name: 'VS Code',
    label: 'VS Code',
    scheme: 'vscode',
    host: VSCODE_EXTENSION_HOST,
    path: VSCODE_EXTENSION_PATH,
    extensionUrl: 'vscode:extension/kilocode.kilo-code',
    downloadUrl: 'https://code.visualstudio.com/download',
    logoSrc: '/logos/vscode.svg',
    alt: 'VS Code Logo',
    visibilityOnInstallPage: 'show',
  },
  {
    source: 'vscode-insiders',
    name: 'VS Code Insiders',
    label: 'VS Code Insiders',
    scheme: 'vscode-insiders',
    host: VSCODE_EXTENSION_HOST,
    path: VSCODE_EXTENSION_PATH,
    extensionUrl: 'vscode-insiders:extension/kilocode.kilo-code',
    downloadUrl: 'https://code.visualstudio.com/insiders/',
    logoSrc: '/logos/vscode-insiders.svg',
    alt: 'VS Code Insiders Logo',
    visibilityOnInstallPage: 'show-when-expanded',
  },
  {
    source: 'cursor',
    name: 'Cursor',
    label: 'Cursor',
    scheme: 'cursor',
    host: VSCODE_EXTENSION_HOST,
    path: VSCODE_EXTENSION_PATH,
    extensionUrl: 'cursor:extension/kilocode.kilo-code',
    downloadUrl: 'https://cursor.sh',
    logoSrc: '/logos/cursor.svg',
    alt: 'Cursor Logo',
    visibilityOnInstallPage: 'show',
  },
  {
    source: 'windsurf',
    name: 'Windsurf',
    label: 'Windsurf',
    scheme: 'windsurf',
    host: VSCODE_EXTENSION_HOST,
    path: VSCODE_EXTENSION_PATH,
    extensionUrl: 'windsurf:extension/kilocode.kilo-code',
    downloadUrl: 'https://www.windsurf.com/',
    logoSrc: '/logos/windsurf_teal_logo.svg',
    alt: 'Windsurf Logo',
    visibilityOnInstallPage: 'show-when-expanded',
  },
  {
    source: 'trae',
    name: 'Trae AI',
    label: 'Trae AI',
    scheme: 'trae',
    host: VSCODE_EXTENSION_HOST,
    path: VSCODE_EXTENSION_PATH,
    extensionUrl: 'trae:extension/kilocode.kilo-code',
    downloadUrl: 'https://www.trae.ai/',
    logoSrc: '/logos/trae_logo.svg',
    alt: 'Trae AI',
    visibilityOnInstallPage: 'show-when-expanded',
  },
  {
    source: 'idea',
    name: 'IntelliJ IDEA',
    label: 'IntelliJ IDEA',
    scheme: 'jetbrains',
    host: 'idea',
    path: JETBRAINS_EXTENSION_PATH,
    extensionUrl: '',
    downloadUrl: 'https://www.jetbrains.com/idea/download/',
    logoSrc: '/logos/idea.svg',
    alt: 'IntelliJ IDEA',
    visibilityOnInstallPage: 'hide',
  },
  {
    source: 'appcode',
    name: 'AppCode',
    label: 'AppCode',
    scheme: 'jetbrains',
    host: 'appcode',
    path: JETBRAINS_EXTENSION_PATH,
    extensionUrl: '',
    downloadUrl: 'https://www.jetbrains.com/objc/download/',
    logoSrc: '/logos/appcode.svg',
    alt: 'AppCode',
    visibilityOnInstallPage: 'hide',
  },
  {
    source: 'clion',
    name: 'CLion',
    label: 'CLion',
    scheme: 'jetbrains',
    host: 'clion',
    path: JETBRAINS_EXTENSION_PATH,
    extensionUrl: '',
    downloadUrl: 'https://www.jetbrains.com/clion/download/',
    logoSrc: '/logos/clion.svg',
    alt: 'CLion',
    visibilityOnInstallPage: 'hide',
  },
  {
    source: 'pycharm',
    name: 'PyCharm',
    label: 'PyCharm',
    scheme: 'jetbrains',
    host: 'pycharm',
    path: JETBRAINS_EXTENSION_PATH,
    extensionUrl: '',
    downloadUrl: 'https://www.jetbrains.com/pycharm/download/',
    logoSrc: '/logos/pycharm.svg',
    alt: 'PyCharm',
    visibilityOnInstallPage: 'hide',
  },
  {
    source: 'phpstorm',
    name: 'phpStorm',
    label: 'phpStorm',
    scheme: 'jetbrains',
    host: 'phpstorm',
    path: JETBRAINS_EXTENSION_PATH,
    extensionUrl: '',
    downloadUrl: 'https://www.jetbrains.com/phpstorm/download/',
    logoSrc: '/logos/phpstorm.svg',
    alt: 'phpStorm',
    visibilityOnInstallPage: 'hide',
  },
  {
    source: 'rubymine',
    name: 'RubyMine',
    label: 'RubyMine',
    scheme: 'jetbrains',
    host: 'rubymine',
    path: JETBRAINS_EXTENSION_PATH,
    extensionUrl: '',
    downloadUrl: 'https://www.jetbrains.com/ruby/download/',
    logoSrc: '/logos/rubymine.svg',
    alt: 'RubyMine',
    visibilityOnInstallPage: 'hide',
  },
  {
    source: 'webstorm',
    name: 'WebStorm',
    label: 'WebStorm',
    scheme: 'jetbrains',
    host: 'webstorm',
    path: JETBRAINS_EXTENSION_PATH,
    extensionUrl: '',
    downloadUrl: 'https://www.jetbrains.com/webstorm/download/',
    logoSrc: '/logos/webstorm.svg',
    alt: 'WebStorm',
    visibilityOnInstallPage: 'hide',
  },
  {
    source: 'rider',
    name: 'Rider',
    label: 'Rider',
    scheme: 'jetbrains',
    host: 'rider',
    path: JETBRAINS_EXTENSION_PATH,
    extensionUrl: '',
    downloadUrl: 'https://www.jetbrains.com/rider/download/',
    logoSrc: '/logos/rider.svg',
    alt: 'Rider',
    visibilityOnInstallPage: 'hide',
  },
  {
    source: 'goland',
    name: 'GoLand',
    label: 'GoLand',
    scheme: 'jetbrains',
    host: 'goland',
    path: JETBRAINS_EXTENSION_PATH,
    extensionUrl: '',
    downloadUrl: 'https://www.jetbrains.com/go/download/',
    logoSrc: '/logos/goland.svg',
    alt: 'GoLand',
    visibilityOnInstallPage: 'hide',
  },
  {
    source: 'rustover',
    name: 'RustOver',
    label: 'RustOver',
    scheme: 'jetbrains',
    host: 'rustover',
    path: JETBRAINS_EXTENSION_PATH,
    extensionUrl: '',
    downloadUrl: 'https://www.jetbrains.com/rust/download/',
    logoSrc: '/logos/rustover.svg',
    alt: 'RustOver',
    visibilityOnInstallPage: 'hide',
  },
  {
    source: 'datagrip',
    name: 'DataGrip',
    label: 'DataGrip',
    scheme: 'jetbrains',
    host: 'datagrip',
    path: JETBRAINS_EXTENSION_PATH,
    extensionUrl: '',
    downloadUrl: 'https://www.jetbrains.com/datagrip/download/',
    logoSrc: '/logos/datagrip.svg',
    alt: 'DataGrip',
    visibilityOnInstallPage: 'hide',
  },
  {
    source: 'dataspell',
    name: 'DataSpell',
    label: 'DataSpell',
    scheme: 'jetbrains',
    host: 'dataspell',
    path: JETBRAINS_EXTENSION_PATH,
    extensionUrl: '',
    downloadUrl: 'https://www.jetbrains.com/dataspell/download/',
    logoSrc: '/logos/dataspell.svg',
    alt: 'DataSpell',
    visibilityOnInstallPage: 'hide',
  },
];

export const DEFAULT_EDITOR = EDITOR_OPTIONS[0]; // vscode
